<?php
$this->headTitle('Update E-mail');

$this->barMenu()->setActiveItemId('profile');

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'My preface' => $this->url('user/profile', ['suffix' => '.html']),
    'Update E-mail' => '',
]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder'=>'name@example.com'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <h1>Update E-mail</h1>
        <p>When E-mail address was updated, your account will been in unactivated status. Please check your email and active your account again.</p>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
