<?php
$this->headTitle('Update password');

$this->barMenu()->setActiveItemId('profile');

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'My profile' => $this->url('user/profile', ['suffix' => '.html']),
    'Update password' => '',
]);

$form->get('old_password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('re_new_password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <h1>Update password</h1>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('old_password')); ?>
            <?php echo $this->formElement($form->get('old_password')); ?>
            <?php echo $this->formElementErrors($form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('new_password')); ?>
            <?php echo $this->formElement($form->get('new_password')); ?>
            <?php echo $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('re_new_password')); ?>
            <?php echo $this->formElement($form->get('re_new_password')); ?>
            <?php echo $this->formElementErrors($form->get('re_new_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
