<?php

$this->headTitle('View profile');

$this->barMenu()->setActiveItemId(null);

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'View profile' => '',
]);
?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?php echo $this->escapeHtml($user->getUid()); ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?php echo $this->escapeHtml($user->getEmail()); ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?php echo $this->escapeHtml($user->getName()); ?></th>
            </tr>
            <tr>
                <th>Created:</th>
                <td><?php echo $this->escapeHtml($user->getCreated()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?php echo $this->escapeHtml($user->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>
