<?php
$this->pageTitleBar('我的订单');
$this->sideTreeMenu()->setActiveId($activeId);

if(!$weChat instanceof \WeChat\Entity\Account) {
    throw new InvalidArgumentException('无公众号信息');
}

$orders = $weChat->getOrders();

$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    //todo
});
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (!$orders->count()) { ?>
            <p>
                <span>您的微信公众号服务到期时间: <strong><?php echo date('Y-m-d', $weChat->getWxExpired()); ?></strong> 是否需要续期? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatAccount', ['action'=>'add-order']); ?>"><i class="fa fa-plus fa-fw"></i> 购买服务</a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/weChatAccount', ['action'=>'add-order']); ?>"><i class="fa fa-plus fa-fw"></i> 购买服务</a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th width="15%">订单号</th>
                            <th width="15%">服务时效</th>
                            <th width="15%">订单金额</th>
                            <th width="15%">状态</th>
                            <th width="40%">操作</th>
                        </tr>
                        <?php
                        foreach ($orders as $order) {
                            if ($order instanceof \WeChat\Entity\Order) {
                                ?>
                                <tr>
                                    <td><?php echo $order->getNo(); ?></td>
                                    <td><strong><?php echo intval($order->getSecond() / (365 * 24 * 3600)); ?></strong> 年</td>
                                    <td><strong><?php echo $order->getMoney(); ?></strong> 元</td>
                                    <td><?php echo $order->getPaidAsString(); ?></td>
                                    <td>
                                        <?php if(\WeChat\Entity\Order::PAID_STATUS_DEFAULT == $order->getPaid()) { ?>
                                        <a class="btn btn-default btn-xs" href="">立即支付</a>
                                        <spa>&nbsp;&nbsp;&nbsp;&nbsp;</spa>
                                        <a class="btn btn-default btn-xs" href="">已经支付</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } } ?>

                    </table>

                </div>
            </div>

        <?php } ?>
    </div>
</div>