<?php
$this->pageTitleBar('我的订单');
$this->sideTreeMenu()->setActiveId($activeId);

if(!$weChat instanceof \WeChat\Entity\Account) {
    throw new InvalidArgumentException('无公众号信息');
}

$orders = $weChat->getOrders();

$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    //todo
});
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (!$orders->count()) { ?>
            <p>
                <span>您的微信公众号服务到期时间: <strong><?php echo date('Y-m-d', $weChat->getWxExpired()); ?></strong> 是否需要续期? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatAccount', ['action'=>'add-order']); ?>"><i class="fa fa-plus fa-fw"></i> 购买服务</a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/weChatAccount', ['action'=>'add-order']); ?>"><i class="fa fa-plus fa-fw"></i> 购买服务</a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th width="15%">订单号</th>
                            <th width="15%">服务时效</th>
                            <th width="15%">订单金额</th>
                            <th width="15%">状态</th>
                            <th width="40%">操作</th>
                        </tr>
                        <?php
                        foreach ($orders as $order) {
                            if ($order instanceof \WeChat\Entity\Order) {
                                ?>
                                <tr>
                                    <td><?php echo $order->getNo(); ?></td>
                                    <td><strong><?php echo intval($order->getSecond() / (365 * 24 * 3600)); ?></strong> 年</td>
                                    <td><strong><?php echo $order->getMoney(); ?></strong> 元</td>
                                    <td><?php echo $order->getPaidAsString(); ?></td>
                                    <td>
                                        <a class="btn btn-default btn-xs" href="#" data-toggle="modal" data-target="#payMessageInfo">支付说明</a>
                                        <?php if(\WeChat\Entity\Order::PAID_STATUS_DEFAULT == $order->getPaid()) { ?>
                                        <spa>&nbsp;&nbsp;&nbsp;&nbsp;</spa>
                                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatAccount', ['action' => 'paid-order', 'key' => $order->getNo()]); ?>">已经支付</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } } ?>

                    </table>

                </div>
            </div>


            <div class="modal" id="payMessageInfo" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">支付说明</h4>
                        </div>
                        <div class="modal-body">
                            <table class="table table-striped">
                                <tr>
                                    <th colspan="2">请完成付款后再点击 "已经支付" 按钮更新状态.</th>
                                </tr>
                                <tr>
                                    <td width="20%">账号:</td>
                                    <td width="80%"><strong>1500 0066 1812 46</strong> </td>
                                </tr>
                                <tr>
                                    <td width="20%">开户行:</td>
                                    <td width="80%">平安银行上海徐家汇支行</td>
                                </tr>
                                <tr>
                                    <td width="20%">账号名:</td>
                                    <td width="80%">宽绩网络科技（上海）有限公司</td>
                                </tr>
                                <tr>
                                    <td width="20%">备注信息:</td>
                                    <td width="80%"><small class="text-muted">您的订单号. 切记要使用正确的订单号.</small></td>
                                </tr>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">我已了解</button>
                        </div>
                    </div>
                </div>
            </div>

        <?php } ?>
    </div>
</div>