<?php
$this->pageTitleBar('给我们反馈');
$this->sideTreeMenu()->setActiveId($activeId);


// 表单: 内容
$input = $form->get('content');
$input->setAttributes([
    'class'=>'form-control',
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '反馈内容不能为空哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_SHORT) {
            $localMessages[$key] = '反馈的内容是不是太少了点? 请再说的详细一点吧, 谢谢!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_LONG) {
            $localMessages[$key] = '我想说是不是太多了点? 这是带给了您多大的仇恨哪. 内容太多了啦!';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content'), '如果您在使用过程中遇到任何困难或者建议, 请让我们知道.'); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
