<?php
$this->pageTitleBar('给我们反馈');
$this->sideTreeMenu()->setActiveId($activeId);

$form->get('content')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content'), '如果您在使用过程中遇到任何困难或者建议, 请让我们知道.'); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
