<?php
$this->pageTitleBar('成员反馈');
$this->sideTreeMenu()->setActiveId($activeId);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
    $(".remove-link").click(function () {
        if(confirm("确定要删除这个反馈么? 删除之后不能再恢复!")) {
            return true;
        } else {
            return false;
        }
    });

    $(".update-reply").click(function () {
        var text = $("#reply_" + $(this).attr("name")).val();
        var url = $(this).data("path");

        $(this).blur();

        $.post(url, {content:text}, function (dt) {
            console.log(dt);
            if(dt.success) {
                window.location.reload(true);
            }
        }, "json");
    });
});

JS;
$this->inlineScript()->captureEnd();

?>

<div class="row">
    <div class="col-lg-12">
        <?php foreach ($rows as $row) { if (!($row instanceof \Admin\Entity\Feedback)) { continue; }  ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h4 class="panel-title">
                                <?php echo $row->getSender()->getMemberName(); ?>
                                <small> 提交于: <em><?php echo $row->getCreated()->format('Y-m-d H:i'); ?></em></small>
                            </h4>
                        </div>
                        <div class="col-lg-4 text-right">
                            <small class=""><a class="remove-link" href="<?php echo $this->url('admin/feedback', ['action' => 'close', 'key' => $row->getId()]); ?>">删除反馈</a></small>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo nl2br($this->escapeHtml($row->getContent())); ?>
                    <hr>
                    <div class="form-group">
                        <textarea id="reply_<?php echo $row->getId(); ?>" class="form-control" cols="80" rows="5"><?php echo $row->getReply(); ?></textarea>
                    </div>
                    <div class="form-group">
                        <input
                                class="btn btn-primary update-reply"
                                name="<?php echo $row->getId(); ?>"
                                data-path="<?php echo $this->url('admin/feedback', ['action' => 'reply', 'key' => $row->getId()]); ?>"
                                type="submit"
                                id="submit"
                                value="Submit">
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>

<?php
if(count($rows)) {
    echo $this->pagination()->render();
}
?>
