<?php
$this->pageTitleBar('成员反馈');
$this->sideTreeMenu()->setActiveId($activeId);
$this->headScript()->appendFile($this->basePath('js/admin/feedback.all.js'));
?>

<div class="row">
    <div class="col-lg-12">
        <?php foreach ($rows as $row) { if (!($row instanceof \Admin\Entity\Feedback)) { continue; }  ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h4 class="panel-title">
                                <?php echo $row->getSender()->getMemberName(); ?>
                                <small> 提交于: <em><?php echo $row->getCreated()->format('Y-m-d H:i'); ?></em></small>
                            </h4>
                        </div>
                        <div class="col-lg-4 text-right">
                            <small class=""><a class="remove-link" href="<?php echo $this->url('admin/feedback', ['action' => 'close', 'key' => $row->getId()]); ?>">删除反馈</a></small>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo nl2br($this->escapeHtml($row->getContent())); ?>
                    <hr>
                    <div class="form-group">
                        <textarea class="form-control" cols="80" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" id="submit" value="Submit">
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>

<?php
if(count($rows)) {
    echo $this->pagination()->render();
}
?>
