<?php
$this->pageTitleBar('我的反馈');
$this->sideTreeMenu()->setActiveId($activeId);

?>


<div class="row">
    <div class="col-lg-12">
        <?php foreach ($rows as $row) { if (!($row instanceof \Admin\Entity\Feedback)) { continue; }  ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h4 class="panel-title">
                                <?php echo $row->getSender()->getMemberName(); ?>
                                <small> 提交于: <em><?php echo $row->getCreated()->format('Y-m-d H:i'); ?></em></small>
                            </h4>
                        </div>
                        <div class="col-lg-4 text-right">
                            <small class=""><a href="<?php echo $this->url('admin/feedback', ['action' => 'cancel', 'key' => $row->getId()]); ?>xxx">删除反馈</a></small>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo nl2br($this->escapeHtml($row->getContent())); ?>
                </div>
            </div>
            <?php if(!empty($row->getReply())) { ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title text-right">
                            <small><em><?php echo $row->getUpdated()->format('Y-m-d H:i'); ?></em> By: </small>
                            <?php echo $row->getReplier()->getMemberName(); ?>
                        </h4>
                    </div>
                    <div class="panel-body">
                        <?php echo nl2br($this->escapeHtml($row->getReply())); ?>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
</div>

<?php
if(count($rows)) {
    echo $this->pagination()->render();
}
?>
