<?php
$this->pageTitleBar('我的反馈');
$this->sideTreeMenu()->setActiveId($activeId);
$this->headScript()->appendFile($this->basePath('js/admin/feedback.all.js'));

?>


<div class="row">
    <div class="col-lg-12">
        <?php foreach ($rows as $row) { if (!($row instanceof \Admin\Entity\Feedback)) { continue; }  ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h4 class="panel-title">
                                <?php echo $row->getSender()->getMemberName(); ?>
                                <small> 提交于: <em><?php echo $row->getCreated()->format('Y-m-d H:i'); ?></em></small>
                            </h4>
                        </div>
                        <div class="col-lg-4 text-right">
                            <small class=""><a class="remove-link" href="<?php echo $this->url('admin/feedback', ['action' => 'delete', 'key' => $row->getId()]); ?>">删除反馈</a></small>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo nl2br($this->escapeHtml($row->getContent())); ?>
                    <?php if(!empty($row->getReply())) { ?>
                        <hr>
                        <p class="text-muted">
                            <em><?php echo $row->getReplier()->getMemberName(); ?> 回复于: <?php echo $row->getUpdated()->format('Y-m-d H:i:s'); ?></em>
                        </p>
                        <div class="text-success"><?php echo nl2br($this->escapeHtml($row->getReply())); ?></div>
                        <p> </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>

<?php
if(count($rows)) {
    echo $this->pagination()->render();
}
?>
