<?php echo $this->doctype(); ?>

<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <?php if('development' == @$appEnv) { ?>
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
    <?php } ?>

    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
        ->prependStylesheet($this->basePath('css/admin/style.css'))
        ->prependStylesheet($this->basePath('open-source-assets/sb-admin-2/css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('open-source-assets/metisMenu/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('open-source-assets/font-awesome-4.7.0/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('open-source-assets/bootstrap-3.3.7-dist/css/bootstrap.min.css'));
    ?>

</head>
<body>

<div id="wrapper">

    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;">
        <div class="navbar-header">
            <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('admin');  ?>">Control Panel</a>
        </div>

        <!-- Top nav bar -->
        <?php echo $this->topRightMenu()->render(); ?>

        <!-- Side nav bar -->
        <?php echo $this->sideTreeMenu()->render(); ?>


    </nav>

    <div id="page-wrapper">
        <!-- Page title bar -->
        <?php echo $this->pageTitleBar()->render(); ?>

        <!-- Page breadcrumb bar -->
        <?php /** echo $this->pageBreadcrumbBar()->render(); */ ?>


        <?php echo $this->content; ?>


    </div>

</div>


<!-- Modal -->
<div class="modal" id="pageModal" tabindex="-1" role="dialog" aria-labelledby="pageModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/admin/form.js'))
    ->prependFile($this->basePath('open-source-assets/sb-admin-2/js/sb-admin-2.js'))
    ->prependFile($this->basePath('open-source-assets/metisMenu/metisMenu.min.js'))
    ->prependFile($this->basePath('open-source-assets/bootstrap-3.3.7-dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('open-source-assets/jquery-3.1.1/jquery-3.1.1.min.js'));
?>

<?php echo $this->inlineScript(); ?>

</body>
</html>
