<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/admin/style.css'))
        ->prependStylesheet($this->basePath('font-awesome-4.6.3/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('bootstrap-3.3.7-dist/css/bootstrap.min.css'));
    ?>

</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
</div>


<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/admin/script.js'))
    ->prependFile($this->basePath('bootstrap-3.3.7-dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.1.0.min.js'));
?>

<?php echo $this->inlineScript(); ?>

</body>
</html>
