<?php
$this->pageTitleBar('Summary');

$this->pageBreadcrumbBar()->addItem('Summary');

?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?php echo $adminer->getAdminId(); ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?php echo $adminer->getAdminEmail(); ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?php echo $this->escapeHtml($adminer->getAdminName()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?php echo $adminer->getAdminStatusAsString(); ?></th>
            </tr>
            <tr>
                <th>Created:</th>
                <td><?php echo $adminer->getAdminCreated(); ?></th>
            </tr>
        </table>
    </div>
</div>