<?php
$this->pageTitleBar('我的信息');

$this->pageBreadcrumbBar()->addItem('Summary');

?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th width="30%">名称</th>
                <th>资料</th>
            </tr>
            <tr>
                <td>登入账号(E-mail):</td>
                <td><?php echo $member->getMemberEmail(); ?></td>
            </tr>
            <tr>
                <td>我的名字:</td>
                <td><?php echo $this->escapeHtml($member->getMemberName()); ?></td>
            </tr>
            <tr>
                <td>我的状态:</td>
                <td><?php echo $member->getMemberStatusAsString(); ?></td>
            </tr>
            <tr>
                <td>账号过期时间:</td>
                <td><?php echo $member->getMemberExpired()->format('Y-m-d'); ?></td>
            </tr>
            <tr>
                <td>账号创建时间:</td>
                <td><?php echo $member->getMemberCreated()->format('Y-m-d'); ?></td>
            </tr>
        </table>
    </div>
</div>