<?php
$this->pageTitleBar('我的信息');

$this->pageBreadcrumbBar()->addItem('Summary');

?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th width="30%">名称</th>
                <th>资料</th>
            </tr>
            <tr>
                <th>登入账号(E-mail):</th>
                <td><?php echo $member->getMemberEmail(); ?></th>
            </tr>
            <tr>
                <th>我的名字:</th>
                <td><?php echo $this->escapeHtml($member->getMemberName()); ?></th>
            </tr>
            <tr>
                <th>我的状态:</th>
                <td><?php echo $member->getMemberStatusAsString(); ?></th>
            </tr>
            <tr>
                <th>账号过期时间:</th>
                <td><?php echo $member->getMemberExpired()->format('Y-m-d'); ?></th>
            </tr>
            <tr>
                <th>账号创建时间:</th>
                <td><?php echo $member->getMemberCreated()->format('Y-m-d'); ?></th>
            </tr>
        </table>
    </div>
</div>