<?php
$this->pageTitleBar('更新我的资料');


$form->get('name')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>

<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

