<?php
$this->headTitle('Active'); // Set page title: Active

$this->barMenu()->setActiveItemId(null); // Cancel actived menu

$this->barBreadcrumbs()->setItems([ // Page breadcrumbs
    'Home' => $this->url('home'),
    'Sign up' => $this->url('user_auth_actions', ['action' => 'sign-up', 'suffix' => '.html']),
    'Active' => '',
]);


$form->setAttributes([
    //'class' => 'form-inline',
    //'style' => 'padding: 30px 10px;',
]);

$form->get('active_code')->setAttributes([
    'class'=>'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Active account</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                <div class="form-group">
                    <?php echo $this->formElement($form->get('csrf')); ?>
                </div>


                <div class="form-group">
                    <?php echo $this->formLabel($form->get('active_code')); ?>
                    <?php echo $this->formElement($form->get('active_code')); ?>
                    <?php echo $this->formElementErrors($form->get('active_code')); ?>
                </div>


                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>





                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>

    </div>
</div>



