<?php
$this->headTitle('Forgot Password'); // Set page title: Active

$this->barMenu()->setActiveItemId(null); // Cancel activated menu

$this->barBreadcrumbs()->setItems([ // Page breadcrumbs
    'Home' => $this->url('home'),
    'Forgot password' => '',
]);


$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com',
]);

$form->get('captcha')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <h1>Forgot password</h1>
        <p>Enter your E-mail address and code to get reset password code</p>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('captcha')); ?>
            <p class="hint">Enter the letters above as you see them.</p>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
