<?php

$this->headTitle('Sign In');

$this->barMenu()->setActiveItemId('guest');

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Sign In' => '',
]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter your password'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);


$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');


$form->prepare();
?>


<div class="row">
    <div class="col-md-6">

        <h1>Please sign in</h1>

        <?php if($isLoginError) { ?>
            <div class="alert alert-warning" role="alert">
                <?php if(2 == $isLoginError) { ?>
                    <strong>Warning!</strong> Please active your account.
                <?php } else { ?>
                    <strong>Warning!</strong> The E-mail and/or Password was mismatched.
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-info" role="alert">
                Please fill out the following form and click the <strong>Sign In</strong> button.
            </div>
        <?php } ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">

            <div class="checkbox">
                <label>
                    <?php echo $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
