<?php
$this->headTitle('Reset Password');

$this->barMenu()->setActiveItemId(null);

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Reset password' => '',
]);


$form->get('password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('re_password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <h1>Reset password</h1>
        <p>Enter your new password</p>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('re_password')); ?>
            <?php echo $this->formElement($form->get('re_password')); ?>
            <?php echo $this->formElementErrors($form->get('re_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
