
<?php
$this->headTitle('Sign Up');

$this->barMenu()->setActiveItemId('guest');

$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Sign up' => '',
]);

//**
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Leo'
]);

$form->get('passwd')->setAttributes([
    'class'=>'form-control'
]);

$form->get('repasswd')->setAttributes([
    'class'=>'form-control'
]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
//*/
$form->prepare();
?>

<h1>Sign up a account</h1>

<p>
    Please fill out the following form and click the <i>Sign Up</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('passwd')); ?>
            <?php echo $this->formElement($form->get('passwd')); ?>
            <?php echo $this->formElementErrors($form->get('passwd')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('repasswd')); ?>
            <?php echo $this->formElement($form->get('repasswd')); ?>
            <?php echo $this->formElementErrors($form->get('repasswd')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
