

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="pageModalLabel"><?php echo $entity->getComName(); ?></h4>
</div>

<style>

</style>

<div class="modal-body">

    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Status</th>
        </tr>
        <?php foreach ($entities as $obj) { if ($obj instanceof \Admin\Entity\Action) { ?>
            <tr>
                <td><?php echo $obj->getActionId(); ?></td>
                <td>
                    <i class="fa fa-<?php echo $obj->getActionIcon(); ?> fa-fw"></i>
                    <?php echo $obj->getActionName(); ?>
                    <small><?php echo $obj->getActionKey(); ?></small>
                </td>
                <td><?php echo $obj->getActionStatusAsString(); ?></td>
            </tr>
        <?php } } ?>
    </table>



</div>


<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>