<?php
$this->pageTitleBar('系统组件');

$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/component.index.js'));

?>

    <div class="row">
        <div class="col-lg-12">
            <p>
                <a id="sync-link" class="btn btn-default" href="<?php echo $this->url('admin/component', ['action'=>'sync']); ?>"><i class="fa fa-refresh fa-fw" ></i> Sync component</a>
            </p>

            <table class="table table-striped">
                <tr>
                    <th>No</th>
                    <th>模块</th>
                    <th>控制器</th>
                    <th>操作</th>
                </tr>

                <?php $i=1; foreach ($rows as $entity) { $pk = urlencode($entity->getComClass()); ?>

                    <tr>
                        <td><?php echo $i++; ?></td>
                        <td><i class="fa fa-<?php echo $entity->getComIcon(); ?> fa-fw" aria-hidden="true"></i> <?php echo $entity->getComName(); ?></td>
                        <td><?php echo substr(strrchr($entity->getComClass(), '\\'), 1); ?></td>
                        <td>
                            <ul class="nav nav-pills actions-list" role="tablist">
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        操作选项 <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a class="danger-link" href="<?php echo $this->url('admin/component', ['action' => 'delete', 'key' => $pk]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> 删除
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/component', ['action' => 'actions', 'key' => $pk]); ?>" data-toggle="modal" data-target="#pageModal">
                                                <i class="fa fa-list fa-fw" aria-hidden="true"></i> 功能接口列表
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>

                <?php } ?>

            </table>

        </div>
    </div>

<?php echo $this->pagination()->render(); ?>