<?php
$this->pageTitleBar('系统组件');

$this->sideTreeMenu()->setActiveId($activeId);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {

    // clean modal data force every time load newest data from server.
    $("#pageModal").on("hidden.bs.modal", function() {
        $(this).removeData("bs.modal");
    });

    $("body").on("click", ".remove-action", function () {
        var tr = $(this).parent().parent();
        if (confirm("确定要删除么? 操作不可恢复!")) {
            var url = $(this).attr("href");
            $(this).blur();
            $.get(url, function (dt) {
                tr.hide();
            });
            return false;
        } else {
            $(this).blur();
            return false;
        }
    });


    $(".danger-link").click(function () {
        if (confirm("确定要删除么? 操作不可恢复!")) {
            return true;
        } else {
            $(this).blur();
            return false;
        }
    });



    $("#sync-link").click(function(){
        if ("disabled" == $(this).attr("disabled")) {
            return false;
        }

        var url = $(this).attr("href");

        $(this).children("i").addClass("fa-spin");
        $(this).attr("href", "#");
        $(this).attr("disabled", true);

        //Ajax post
        $.get(url, function (dt) {
            if (!dt.success) {
                alert(dt.message);
            } else {
                location.reload();
            }
        }, 'json');

        return false;
    });
});

JS;
$this->inlineScript()->captureEnd();

?>

    <div class="row">
        <div class="col-lg-12">
            <p>
                <a id="sync-link" class="btn btn-default" href="<?php echo $this->url('admin/component', ['action'=>'sync']); ?>"><i class="fa fa-refresh fa-fw" ></i> Sync component</a>
            </p>

            <table class="table table-striped">
                <tr>
                    <th>No</th>
                    <th>模块</th>
                    <th>控制器</th>
                    <th>操作</th>
                </tr>

                <?php $i=1; foreach ($rows as $entity) { $pk = urlencode($entity->getComClass()); ?>

                    <tr>
                        <td><?php echo $i++; ?></td>
                        <td><i class="fa fa-<?php echo $entity->getComIcon(); ?> fa-fw" aria-hidden="true"></i> <?php echo $entity->getComName(); ?></td>
                        <td><?php echo substr(strrchr($entity->getComClass(), '\\'), 1); ?></td>
                        <td>
                            <ul class="nav nav-pills actions-list" role="tablist">
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        操作选项 <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a class="danger-link" href="<?php echo $this->url('admin/component', ['action' => 'delete', 'key' => $pk]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> 删除
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/component', ['action' => 'actions', 'key' => $pk]); ?>" data-toggle="modal" data-target="#pageModal">
                                                <i class="fa fa-list fa-fw" aria-hidden="true"></i> 功能接口列表
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>

                <?php } ?>

            </table>

        </div>
    </div>

<?php echo $this->pagination()->render(); ?>