<?php
$this->pageTitleBar('权限配置', '分组权限: ' . $dept->getDeptName());

$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/acl.js'));

?>

<div class="row">
    <?php
    foreach ($components as $component) {
        if ($component instanceof \Admin\Entity\Component && array_key_exists($component->getComClass(), $actions)) {
            ?>
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-<?php echo $component->getComIcon(); ?> fa-fw"></i>
                        <?php echo $component->getComName(); ?>
                    </div>
                    <div class="panel-body">
                        <table class="table table-hover">
                            <?php
                            $url = urldecode($this->url('admin/acl', ['action' => 'acl-department-dispatch', 'key' => $dept->getDeptId() . '-%d-%d']));
                            foreach ($actions[$component->getComClass()] as $action) {
                                if ($action instanceof \Admin\Entity\Action) {
                                    $actionId = $action->getActionId();
                                    $disabled = (\Admin\Entity\Action::STATUS_VALIDITY == $action->getActionStatus()) ? false : true;
                                    ?>
                                    <tr>
                                        <td>
                                            <span class="<?php echo $disabled ? 'color-disabled': ''; ?>">
                                                <i class="fa fa-<?php echo $action->getActionIcon(); ?> fa-fw"></i>
                                                <?php echo $action->getActionName(); ?>
                                            </span>
                                        </td>
                                        <td class="text-right">
                                            <select class="action-status"<?php echo $disabled ? ' disabled="disabled"': ''; ?>>
                                                <?php $list = \Admin\Entity\AclDepartment::getAclStatusList(); ?>
                                                <?php if(!array_key_exists($actionId, $acls)) { ?>
                                                    <?php foreach ($list as $k => $v) { ?>
                                                        <option value="<?php echo sprintf($url, $actionId, $k); ?>"<?php echo \Admin\Entity\AclDepartment::STATUS_FORBIDDEN == $k ? ' selected' : ''; ?>><?php echo $v; ?></option>
                                                    <?php } ?>
                                                <?php } else { ?>
                                                    <?php $acl = $acls[$actionId]; ?>
                                                    <?php foreach ($list as $k => $v) { ?>
                                                        <option value="<?php echo sprintf($url, $actionId, $k); ?>"<?php echo $acl->getStatus() == $k ? ' selected' : ''; ?>><?php echo $v; ?></option>
                                                    <?php } ?>
                                                <?php } ?>
                                            </select>
                                        </td>
                                    </tr>
                                <?php } } ?>
                        </table>
                    </div>
                </div>
            </div>
        <?php } } ?>

</div>
<?php echo $this->pagination()->render(); ?>
