<?php
$this->pageTitleBar('权限配置', '分组权限');

$this->sideTreeMenu()->setActiveId($activeId);

?>

    <div class="row">
        <div class="col-lg-12">

            <table class="table table-striped">
                <tr>
                    <th>Department</th>
                    <th>Members</th>
                    <th>Actions</th>
                </tr>

                <?php foreach ($entities as $dept) { ?>

                    <tr>
                        <td><?php echo $dept->getDeptName(); ?></td>
                        <td><?php echo $dept->getDeptMembers(); ?></td>
                        <td>
                            <?php if($dept->getDeptId() > 1) { ?>
                                <a href="<?php echo $this->url('admin/acl', ['action' => 'acl-department', 'key' => $dept->getDeptId()]); ?>">ACL Setting</a>
                            <?php } ?>
                        </td>
                    </tr>

                <?php } ?>

            </table>


        </div>
    </div>

<?php echo $this->pagination()->render(); ?>