<?php
$this->pageTitleBar('权限配置', '分组权限: ' . $dept->getDeptName());

$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/acl.js'));

?>

<div class="row">
<?php foreach ($components as $component) { if ($component instanceof \Admin\Entity\Component) { ?>

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-<?php echo $component->getComIcon(); ?> fa-fw"></i>
                <?php echo $component->getComName(); ?>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                <?php
                $url = urldecode($this->url('admin/acl', ['action' => 'department-dispatch', 'key' => $dept->getDeptId() . '_%s_%d']));
                $actions = $component->getActions();
                foreach ($actions as $action) { if ($action instanceof \Admin\Entity\Action) { $actionId = $action->getActionId();
                ?>
                    <tr>
                        <td>
                            <i class="fa fa-<?php echo $action->getActionIcon(); ?> fa-fw"></i>
                            <?php echo $action->getActionName(); ?>
                        </td>
                        <td class="text-right">
                            <select class="action-status">
                            <?php
                            $list = \Admin\Entity\AclDepartment::getAclStatusList();
                            if(!array_key_exists($actionId, $acl)) { foreach ($list as $k => $v) {
                            ?>
                                <option value="<?php echo sprintf($url, $actionId, $k); ?>"<?php echo \Admin\Entity\AclDepartment::STATUS_FORBIDDEN == $k ? ' selected' : ''; ?>><?php echo $v; ?></option>
                            <?php } } else {  $aclDepartment = $acl[$actionId]; foreach ($list as $k => $v) { ?>
                                <option value="<?php echo sprintf($url, $actionId, $k); ?>"<?php echo $aclDepartment->getStatus() == $k ? ' selected' : ''; ?>><?php echo $v; ?></option>
                            <?php } } ?>
                            </select>
                        </td>
                    </tr>
                <?php } } ?>
                </table>
            </div>
        </div>
    </div>
<?php } } ?>

</div>
<?php echo $this->pagination()->render(); ?>
