<?php
$this->pageTitleBar('权限配置', '个人权限');

$this->sideTreeMenu()->setActiveId($activeId);

?>

    <div class="row">
        <div class="col-lg-12">

            <table class="table table-striped">
                <tr>
                    <th>成员名</th>
                    <th>登入账号</th>
                    <th>等级</th>
                    <th>权限配置</th>
                </tr>
                <?php
                foreach ($entities as $member) {
                    if ($member instanceof \Admin\Entity\Member) {
                        if($member->getMemberId() == \Admin\Entity\Member::DEFAULT_MEMBER_ID) { continue; }
                ?>
                    <tr>
                        <td><?php echo $member->getMemberName(); ?></td>
                        <td><?php echo $member->getMemberEmail(); ?></td>
                        <td><?php echo $member->getMemberLevelAsString(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('admin/acl', ['action' => 'member', 'key' => $member->getMemberId()]); ?>">进入个人权限配置</a>
                        </td>
                    </tr>

                <?php } } ?>

            </table>


        </div>
    </div>

<?php echo $this->pagination()->render(); ?>