<?php
$this->pageTitleBar('公众号菜单列表');
$this->sideTreeMenu()->setActiveId($activeId);


$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    $(".delete").click(function () {
        if(confirm("确定要删除这个菜单么? 删除后立即生效, 不可恢复!")) {
            return true;
        } else {
            return false;
        }
    });
});
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (empty($menus)) { ?>
            <p>
                <span>您的微信公众号还没有创建自定义菜单, 是否需要现在创建? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw"></i> 添加自定义菜单</a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw"></i> 添加菜单</a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th>菜单名称</th>
                            <th>菜单类型</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                        <?php
                        foreach ($menus as $menu) {
                            if ($menu instanceof \Admin\Entity\WeChatMenu) {
                                ?>
                                <tr>
                                    <td><?php echo $menu->getName(); ?></td>
                                    <td><?php echo $menu->getTypeAsString(); ?></td>
                                    <td><?php echo $menu->getUpdated()->format('Y-m-d H:i:s'); ?></td>
                                    <td>
                                        <a class="delete" href="<?php echo $this->url('admin/weChatMenu', ['action' => 'delete', 'key' => $menu->getId()]); ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } } ?>

                    </table>

                </div>
            </div>

        <?php } ?>
    </div>
</div>

<?php echo $this->pagination()->render(); ?>

