<?php
$this->pageTitleBar('公众号菜单列表');
$this->sideTreeMenu()->setActiveId($activeId);


$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    $(".delete").click(function () {
        if(confirm("确定要删除这个菜单么? 删除后立即生效, 不可恢复! \\n删除本地菜单不影响公众号现有的菜单配置.")) {
            return true;
        } else {
            return false;
        }
    });
    
    $(".import").click(function() {
        
        var target = $(this);
        var url = target.attr("href");
        if(url.length < 2) {
            return false;
        }
        
        if(confirm("导入微信公众号目前的菜单信息后, 本地已有的菜单将被全部删除. 确定要导入么?")) {
            target.attr("href", "");
            $.get(url, function(dt) {
                if(!dt.success) {
                    target.attr("href", url);
                    alert(dt.message);
                } else {
                    alert(dt.message);
                    window.location.reload(true);
                }
            });
            
            $(this).blur();
            return false;
        } 
        $(this).blur();
        return false;
    });
    
    $(".trash").click(function() {
        
        var target = $(this);
        var url = target.attr("href");
        if(url.length < 2) {
            return false;
        }
        
        if(confirm("清空微信公众号目前的菜单信息后, 用户进入公众号将不再显示底部菜单. 确定要清空么?")) {
            target.attr("href", "");
            $.get(url, function(dt) {
                if(!dt.success) {
                    target.attr("href", url);
                    alert(dt.message);
                } else {
                    alert(dt.message);
                    window.location.reload(true);
                }
            });
            
            $(this).blur();
            return false;
        } 
        $(this).blur();
        return false;
    });
    
    
    $(".async").click(function() {
        var target = $(this);
        var url = target.attr("href");
        if(url.length < 10) {
            $(this).blur();
            return false;
        }
        if(confirm("同步微信公众号 自定义菜单, 将覆盖之前公众号的所有菜单(自定义菜单+个性化菜地)配置. 需要进行么?")) {
            alert("同步过程可能需要点时间. 请耐心等待. 同步成功. 页面会刷新! 点确定开始同步.");
            target.attr("href", "");
            $.get(url, function(dt) {
                if(!dt.success) {
                    target.attr("href", url);
                    alert(dt.message);
                } else {
                    alert(dt.message);
                    window.location.reload(true);
                }
            });
            return false;
        }
        $(this).blur();
        return false;
    });
});
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (empty($menus)) { ?>
            <p>
                <span>您的微信公众号还没有创建自定义菜单, 是否需要现在创建? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'add']); ?>">
                    <i class="fa fa-plus fa-fw"></i> 添加自定义菜单
                </a>
                <span> &nbsp;&nbsp; </span>
                <a class="btn btn-default btn-xs import" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'import']); ?>">
                    <i class="fa fa-share fa-fw" aria-hidden="true"></i> 导入微信公众号现有菜单
                </a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'add']); ?>">
                            <i class="fa fa-plus fa-fw"></i> 添加本地菜单
                        </a>
                        <span> &nbsp;&nbsp; </span>
                        <a class="btn btn-default btn-sm import" href="<?php echo $this->url('admin/weChatMenu', ['action'=>'import']); ?>">
                            <i class="fa fa-share fa-fw" aria-hidden="true"></i> 导入微信公众号现有菜单
                        </a>
                        <span> &nbsp;&nbsp; </span>
                        <a class="btn btn-default btn-sm trash" href="<?php echo $this->url('admin/weChatMenu', ['action' => 'trash']); ?>">
                            <i class="fa fa-trash fa-fw" aria-hidden="true"></i> 清空微信公众号现有菜单
                        </a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th>菜单名称</th>
                            <th>菜单类型</th>
                            <th>菜单状态</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                        <?php
                        foreach ($menus as $menu) {
                            if ($menu instanceof \WeChat\Entity\Menu) {
                                ?>
                                <tr>
                                    <td><?php echo $menu->getName(); ?></td>
                                    <td><?php echo $menu->getTypeAsString(); ?></td>
                                    <td>
                                        <?php if(\WeChat\Entity\Menu::STATUS_ACTIVATED == $menu->getStatus()) { ?>
                                            <span class="label label-success">
                                        <?php } else { ?>
                                            <span class="label label-default">
                                        <?php } ?>
                                        <?php echo $menu-> getStatusAsString(); ?>
                                            </span>
                                    </td>
                                    <td><?php echo $menu->getUpdated()->format('Y-m-d H:i:s'); ?></td>
                                    <td>
                                        <a class="async" href="<?php echo $this->url('admin/weChatMenu', ['action' => 'async', 'key' => $menu->getId()]); ?>">
                                            <?php if($menu->getType() == \WeChat\Entity\Menu::TYPE_CONDITIONAL) { ?>
                                                <?php if($menu->getStatus() == \WeChat\Entity\Menu::STATUS_ACTIVATED) { ?>
                                                    删除<strong>个性化菜单</strong>
                                                <?php } else { ?>
                                                    添加<strong>个性化菜单</strong>
                                                <?php } ?>
                                            <?php } else { ?>
                                                同步<strong>自定义菜单</strong>
                                            <?php } ?>
                                        </a>
                                        <span> | </span>
                                        <a href="<?php echo $this->url('admin/weChatMenu', ['action' => 'edit', 'key' => $menu->getId()]); ?>">编辑</a>
                                        <?php if($menu->getStatus() == \WeChat\Entity\Menu::STATUS_RETIRED) { ?>
                                        <span> | </span>
                                        <a class="delete" href="<?php echo $this->url('admin/weChatMenu', ['action' => 'delete', 'key' => $menu->getId()]); ?>">删除</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } } ?>

                    </table>

                </div>
            </div>

        <?php } ?>
    </div>
</div>

<?php echo $this->pagination()->render(); ?>

