<?= $this->doctype() ?>

<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>

        <?php echo $this->headTitle('Btz Application')->setSeparator(' - ')->setAutoEscape(false); ?>

        <!-- styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('font-awesome-4.6.3/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bootstrap-3.3.7-dist/css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('bootstrap-3.3.7-dist/css/bootstrap.min.css'))
        ?>

    </head>
    <body>

        <div class="container">

            <div class="row">
                <div class="col-md-4">
                    <div class="app-caption" style="color: #fff;">Nobody can found me!</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    if(isset($activeMenuItemId)) {
                        $this->barMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render navigation bar
                    echo $this->barMenu()->render();
                    ?>

                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?php
                    echo $this->barBreadcrumbs()->render();
                    ?>

                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <hr>
            <footer>
                <p>&copy 2015 - <?php echo date('Y') ?> by Btz Ltd. All rights reserved.</p>
            </footer>
        </div>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('bootstrap-3.3.7-dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'));
        ?>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
