<?php echo $this->doctype(); ?>

<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>

        <?php echo $this->headTitle('微信接口服务')->setSeparator(' - ')->setAutoEscape(false); ?>

        <!-- styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
            //->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('open-source-assets/font-awesome-4.7.0/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('open-source-assets/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('open-source-assets/bootstrap-3.3.7-dist/css/bootstrap.min.css'));
        ?>

        <style>
            .main-menu > li > a:first-child {
                padding-top: 10px;
                padding-bottom: 11px;
            }
        </style>

    </head>
    <body>

        <div class="container">

            <div class="row">
                <div class="col-md-4">
                    <div class="app-caption" style="color: #fff;">Nobody can found me!</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    if(isset($activeMenuItemId)) {
                        $this->barMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render navigation bar
                    echo $this->barMenu()->render();
                    ?>

                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?php
                    echo $this->barBreadcrumbs()->render();
                    ?>

                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <hr>
            <footer>
                <p>&copy 2015 - <?php echo date('Y') ?> 宽绩网络科技 版权所有. 备案号: <a href="http://www.miitbeian.gov.cn/" target="_blank">沪ICP备17005838号-1</a>.</p>
            </footer>
        </div>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('open-source-assets/bootstrap-3.3.7-dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('open-source-assets/jquery-3.1.1/jquery-3.1.1.min.js'));
        ?>

        <?php echo $this->inlineScript(); ?>

        <script type="text/javascript">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-8692007-2', 'auto');
            ga('send', 'pageview');

        </script>
    </body>
</html>
