<?php
$this->pageTitleBar('站内广播');

$this->sideTreeMenu()->setActiveId($activeId);


// 表单: 标题
$input = $form->get('topic');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder' => '这里填写消息标题',
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '消息标题不能为空哦!',
    \Zend\Validator\StringLength::TOO_SHORT => '消息标题太短了哦!',
    \Zend\Validator\StringLength::TOO_LONG => '消息标题太长了哦!',
]);

// 表单: 内容
$input = $form->get('content');
$input->setAttributes([
    'class'=>'form-control',
    'rows' => 6,
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '消息内容不能为空哦!',
    \Zend\Validator\StringLength::TOO_SHORT => '消息内容太短了哦!',
    \Zend\Validator\StringLength::TOO_LONG => '消息内容太长了哦!',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>

<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('topic'), '消息标题'); ?>
            <?php echo $this->formElement($form->get('topic')); ?>
            <?php echo $this->formElementErrors($form->get('topic')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content'), '消息内容'); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
