<?php
$this->pageTitleBar('站内广播');

$this->sideTreeMenu()->setActiveId($activeId);

$form->get('topic')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter the message topic'
]);

$form->get('content')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('topic')); ?>
            <?php echo $this->formElement($form->get('topic')); ?>
            <?php echo $this->formElementErrors($form->get('topic')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content')); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
