<?php
$this->pageTitleBar('群发消息');

$this->sideTreeMenu()->setActiveId($activeId);

$this->headLink()->appendStylesheet($this->basePath('open-source-assets/bootcomplete/bootcomplete.css'));
$this->headScript()->appendFile($this->basePath('open-source-assets/bootcomplete/jquery.bootcomplete.js'));
$this->headScript()->appendFile($this->basePath('js/admin/message.send.js'));

$autoSuggestUrl = $this->url('admin/search', ['action' => 'depts']);
$this->inlineScript()->captureStart();
echo <<<JS
    var autoSuggestUrl = "$autoSuggestUrl";
JS;
$this->inlineScript()->captureEnd();


$form->get('receiver_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '选择接收部门',
    'autocomplete' => 'off',
]);



$form->get('topic')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '输入消息标题'
]);

$form->get('content')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('receiver_name'), '接收部门'); ?>
            <?php echo $this->formElement($form->get('receiver_name')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_name')); ?>
            <?php echo $this->formElement($form->get('receiver_id')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_id')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('topic')); ?>
            <?php echo $this->formElement($form->get('topic')); ?>
            <?php echo $this->formElementErrors($form->get('topic')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content')); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
