<?php
$this->pageTitleBar('群发消息');

$this->sideTreeMenu()->setActiveId($activeId);


if (!$receiver instanceof \Admin\Entity\Department) {
    throw new \Admin\Exception\InvalidArgumentException('无效的参数');
}


// 表单: 消息接收者
$input = $form->get('receiver_id');
$input->setAttributes([
    'value' => $receiver->getDeptId(),
]);
$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Admin\Validator\DeptIdValidator::ID_INVALID) {
            $localMessages[$key] = '无效的接收者分组!';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}


$input = $form->get('receiver_name');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder' => '接收分组名称',
    'autocomplete' => 'off',
    'value' => $receiver->getDeptName(),
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '接收者不能为空哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_SHORT) {
            $localMessages[$key] = '接收者名字太短了哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_LONG) {
            $localMessages[$key] = '接收者名字太长了哦!';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}


// 表单: 标题
$input = $form->get('topic');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder' => '这里填写消息标题',
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '消息标题不能为空哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_SHORT) {
            $localMessages[$key] = '消息标题太短了哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_LONG) {
            $localMessages[$key] = '消息标题太长了哦!';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}


// 表单: 内容
$input = $form->get('content');
$input->setAttributes([
    'class'=>'form-control',
    'rows' => 6,
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '消息内容不能为空哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_SHORT) {
            $localMessages[$key] = '消息内容太短了哦!';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_LONG) {
            $localMessages[$key] = '消息内容太长了哦!';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}


$this->headLink()->appendStylesheet($this->basePath('open-source-assets/bootcomplete/bootcomplete.css'));
$this->headScript()->appendFile($this->basePath('open-source-assets/bootcomplete/jquery.bootcomplete.js'));

$autoSuggestUrl = $this->url('admin/search', ['action' => 'depts']);


$this->inlineScript()->captureStart();
echo <<<JS

var autoSuggestUrl = "$autoSuggestUrl";

$(function () {
    $("#receiver_name").bootcomplete({
        url: autoSuggestUrl,
        method: "post",
        idField: true,
        idFieldName: 'receiver_id',
        minLength: 1
    });
});

JS;
$this->inlineScript()->captureEnd();


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('receiver_name'), '广播分组'); ?>
            <?php echo $this->formElement($form->get('receiver_name')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_name')); ?>
            <?php echo $this->formElement($form->get('receiver_id')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_id')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('topic'), '消息标题'); ?>
            <?php echo $this->formElement($form->get('topic')); ?>
            <?php echo $this->formElementErrors($form->get('topic')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content'), '消息内容'); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
