<?php
$this->pageTitleBar('收件箱');
$this->sideTreeMenu()->setActiveId($activeId);

?>


<div class="row">
    <div class="col-lg-12">

        <table class="table table-hover">
            <tr>
                <th width="40"><i class="fa fa-square-o fa-fw"></i></th>
                <th width="40"><i class="fa fa-envelope-open-o fa-fw" aria-hidden="true"></i></th>
                <th width="100">发送者</th>
                <th>主题</th>
                <th>时间</th>
            </tr>
            <?php foreach($rows as $row) { if ($row instanceof \Admin\Entity\MessageBox) { ?>
                <tr>
                    <td><i class="fa fa-square-o fa-fw"></i></td>
                    <td>
                        <?php if(\Admin\Entity\MessageBox::STATUS_RECEIVER_UNREAD == $row->getReceiverStatus()) { ?>
                            <i class="fa fa-envelope-o fa-fw"></i>
                        <?php } else { ?>
                            <i class="fa fa-envelope-open-o fa-fw"></i>
                        <?php } ?>
                    </td>
                    <td><?php echo \Admin\Entity\MessageBox::MESSAGE_TYPE_BROADCAST == $row->getType() ? '系统' : $row->getSenderName(); ?></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#<?php echo $row->getId(); ?>">
                        <?php if(\Admin\Entity\MessageBox::STATUS_RECEIVER_UNREAD == $row->getReceiverStatus()) { ?>
                            <span class="weight"><?php echo $row->getContent()->getTopic(); ?></span>
                        <?php } else { ?>
                            <span><?php echo $row->getContent()->getTopic(); ?></span>
                        <?php } ?>
                        </a>
                    </td>
                    <td><?php echo $row->getCreated()->format('Y-m-d H:i:s'); ?></td>
                    <div class="modal" id="<?php echo $row->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title"><?php echo $row->getContent()->getTopic(); ?></h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $row->getContent()->getContent(); ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    <button type="button" class="btn btn-primary">删除消息</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php } } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>
