<?php
$this->pageTitleBar('收件箱');
$this->sideTreeMenu()->setActiveId($activeId);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
    $(".message-modal").on("shown.bs.modal", function (e) {

        $(e.relatedTarget).html($(e.relatedTarget).text());
        var url = $(e.relatedTarget).data("ajaxcall");

        $(e.relatedTarget).parent().prev().prev().children('i').removeClass("fa-envelope-o").addClass("fa-envelope-open-o");

        if(url.length > 36) {
            $.get(url, function (dt) {
                console.log(dt);
            }, "json");
            $(e.relatedTarget).data("ajaxcall", "");
        }

    });

    $(".message-modal").on("hidden.bs.modal", function () {
        window.setTimeout(function () {
            $(".show-message-content").each(function () {
                $(this).blur();
            });
        }, 100);
    });

    $(".delete-message-dialog").click(function () {
        var dialogId = $(this).data("target");
        var url = $(this).data("ajaxcall");
        $.get(url, function (dt) {
            if(dt.success) {
                window.setTimeout(function () {
                    $("#box_" + dialogId).hide();
                }, 500);
            }
            console.log(dt);
        }, 'json');
        $('#' + dialogId).modal('hide');
    });
});

JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">

        <table class="table table-hover">
            <tr>
                <th width="40"><i class="fa fa-square-o fa-fw"></i></th>
                <th width="40"><i class="fa fa-envelope-open-o fa-fw" aria-hidden="true"></i></th>
                <th width="100">发送者</th>
                <th>主题</th>
                <th>时间</th>
            </tr>
            <?php
            foreach($rows as $row) {
                if ($row instanceof \Admin\Entity\MessageBox) {
                    $unread = \Admin\Entity\MessageBox::STATUS_RECEIVER_UNREAD == $row->getReceiverStatus();
                    $systemMsg = \Admin\Entity\MessageBox::MESSAGE_TYPE_BROADCAST == $row->getType();

                    if (\Admin\Entity\MessageContent::STATUS_VALIDITY == $row->getContent()->getStatus()) {
                        $topic = $this->escapeHtml($row->getContent()->getTopic());
                        $content = nl2br($this->escapeHtml($row->getContent()->getContent()));
                    } else {
                        $topic = '消息已过期';
                        $content = '此消息已经过期, 无法再被查阅!';
                    }

                    $readUrl = !$unread ? '':$this->url('admin/message', ['action' => 'read', 'key' => $row->getId()]);
                    $deleteUrl = $this->url('admin/message', ['action' => 'delete', 'key' => $row->getId()]);
            ?>
                <tr id="box_<?php echo $row->getId(); ?>">
                    <td><i class="fa fa-square-o fa-fw"></i></td>
                    <td><i class="fa fa-envelope<?php echo $unread ? '' : '-open'; ?>-o fa-fw"></i></td>
                    <td><?php echo $systemMsg ? '系统' : $row->getSenderName(); ?></td>
                    <td>
                        <a class="show-message-content" href="#" data-ajaxcall="<?php echo $readUrl; ?>" data-toggle="modal" data-target="#<?php echo $row->getId(); ?>">
                            <?php echo $unread ? '<strong>' . $topic . '</strong>' : $topic; ?>
                        </a>
                    </td>
                    <td><?php echo $row->getCreated()->format('Y-m-d H:i:s'); ?></td>
                    <div class="modal message-modal" id="<?php echo $row->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title"><?php echo $topic; ?></h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $content; ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    <button type="button"
                                            class="btn btn-primary delete-message-dialog"
                                            data-target="<?php echo $row->getId(); ?>"
                                            data-ajaxcall="<?php echo $deleteUrl; ?>"
                                    >删除消息</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php } } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>
