<?php
$this->pageTitleBar('消息内容管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/message.index.js'));

?>


<div class="row">
    <div class="col-lg-12">

        <table class="table table-hover">
            <tr>
                <th>主题</th>
                <th>时间</th>
                <th>操作</th>
            </tr>
            <?php
            foreach($rows as $row) {
                if ($row instanceof \Admin\Entity\MessageContent) {
                    $topic = $this->escapeHtml($row->getTopic());
                    $content = nl2br($this->escapeHtml($row->getContent()));
            ?>
                <tr>
                    <td>
                        <a class="show-message-content" href="#" data-toggle="modal" data-target="#<?php echo $row->getId(); ?>">
                            <?php echo $topic; ?>
                        </a>
                    </td>
                    <td><?php echo $row->getCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td>
                        <a class="close-message" href="<?php echo $this->url('admin/message', ['action' => 'close', 'key' => $row->getId()]); ?>">
                            <i class="fa fa-close fa-fw" aria-hidden="true"></i> 删除
                        </a>
                    </td>
                    <div class="modal message-modal" id="<?php echo $row->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title"><?php echo $topic; ?></h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $content; ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php } } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>
