<?php
$this->pageTitleBar('全部消息管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
    $(".message-modal").on("hidden.bs.modal", function () {
        window.setTimeout(function () {
            $(".show-message-content").each(function () {
                $(this).blur();
            });
        }, 100);
    });

    $(".close-message").click(function () {
        var url = $(this).attr("href");
        var curLine = $(this).parent().parent();
        if(confirm("确定关闭此条消息么? 所有拥有此消息的人均无法再查阅!")) {
            $.get(url, function (dt) {
                console.log(dt);
                if(dt.success) {
                    curLine.hide();
                } else {
                    alert(dt.message);
                }
            }, 'json');
        }

        return false;
    });
});

JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">

        <table class="table table-hover">
            <tr>
                <th>主题</th>
                <th>时间</th>
                <th>操作</th>
            </tr>
            <?php
            foreach($rows as $row) {
                if ($row instanceof \Admin\Entity\MessageContent) {
                    $topic = $this->escapeHtml($row->getTopic());
                    $content = nl2br($this->escapeHtml($row->getContent()));
            ?>
                <tr>
                    <td>
                        <a class="show-message-content" href="#" data-toggle="modal" data-target="#<?php echo $row->getId(); ?>">
                            <?php echo $topic; ?>
                        </a>
                    </td>
                    <td><?php echo $row->getCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td>
                        <a class="close-message" href="<?php echo $this->url('admin/message', ['action' => 'close', 'key' => $row->getId()]); ?>">
                            <i class="fa fa-close fa-fw" aria-hidden="true"></i> 删除
                        </a>
                    </td>
                    <div class="modal message-modal" id="<?php echo $row->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title"><?php echo $topic; ?></h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $content; ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php } } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>
