<?php
$this->pageTitleBar('发送消息');

$this->sideTreeMenu()->setActiveId($activeId);

$this->headLink()->appendStylesheet($this->basePath('open-source-assets/bootcomplete/bootcomplete.css'));
$this->headScript()->appendFile($this->basePath('open-source-assets/bootcomplete/jquery.bootcomplete.js'));

$autoSuggestUrl = $this->url('admin/search', ['action' => 'members']);

$form->get('receiver_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '接收人名称',
    'autocomplete' => 'off',
]);


$form->get('topic')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '输入消息标题'
]);

$form->get('content')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

$this->inlineScript()->captureStart();
echo <<<JS

var autoSuggestUrl = "$autoSuggestUrl";

$(function () {
    $("#receiver_name").bootcomplete({
        url: autoSuggestUrl,
        method: "post",
        idField: true,
        idFieldName: 'receiver_id',
        minLength: 1
    });
});

JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('receiver_name'), '接收者'); ?>
            <?php echo $this->formElement($form->get('receiver_name')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_name')); ?>
            <?php echo $this->formElement($form->get('receiver_id')); ?>
            <?php echo $this->formElementErrors($form->get('receiver_id')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('topic')); ?>
            <?php echo $this->formElement($form->get('topic')); ?>
            <?php echo $this->formElementErrors($form->get('topic')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content')); ?>
            <?php echo $this->formElement($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
