<?php
$this->pageTitleBar('申请二维码');

$this->sideTreeMenu()->setActiveId($activeId);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '二维码名称'
]);

$form->get('type')->setAttributes([
    'class' => 'form-control qrcode-type',
]);

$form->get('expired')->setAttributes([
    'class' => 'form-control',
    'value' => 604800,
    'placeholder' => '有效时间(秒)',
]);

$form->get('scene')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '二维码参数',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();


$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    $(".qrcode-type").change(function () {
        if("none" == $("#expired-row").css("display")) {
            $("#expired-row").show();
        } else {
            $("#expired-row").hide();
        }
    });
})
JS;
$this->inlineScript()->captureEnd();


?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'), '设置二维码名称'); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('type'), '设置二维码类型'); ?>
            <?php echo $this->formElement($form->get('type')); ?>
            <?php echo $this->formElementErrors($form->get('type')); ?>
        </div>

        <div class="form-group" id="expired-row">
            <?php echo $this->formLabel($form->get('expired'), '设置二维码有效时间'); ?>
            <?php echo $this->formElement($form->get('expired')); ?>
            <p class="text-muted">
                <small>有效时间为从现在开始的秒数, 比如设定有效时间为一个小时: <strong>3600</strong>.<br />临时二维码最长有效时间为7天(即 604800 秒)</small>
            </p>
            <?php echo $this->formElementErrors($form->get('expired')); ?>
        </div>


        <div class="form-group">
            <?php echo $this->formLabel($form->get('scene'), '设置二维码参数'); ?>
            <?php echo $this->formElement($form->get('scene')); ?>
            <p class="text-muted">
                <small>临时二维码: 可以设置一个数字, 最大值: 4294967296.<br />
                    永久二维码: 可以设置一个 1 - 100000内的数字或者一个64位长度内的任意字符串</small>
            </p>
            <?php echo $this->formElementErrors($form->get('scene')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
