<?php
$this->pageTitleBar('制作二维码');
$this->sideTreeMenu()->setActiveId($activeId);

?>

<?php
if (!$qrCode instanceof \Admin\Entity\WeChatQrCode) {
    echo 'System error!';
} else {
?>

    <div class="row">
        <div class="col-lg-6">
            <p>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/weChatQrCode'); ?>"><i class="fa fa-reply fa-fw" aria-hidden="true"></i> 返回</a>
            </p>

            <form method="post" target="_blank" action="<?php echo $this->url('admin/weChatQrCode', ['action' => 'download', 'suffix' => '.html']); ?>">
                <div class="form-group">
                    <input type="hidden" name="qr_value" value="<?php echo urlencode($qrCode->getUrl()); ?>">
                    <label for="qr_type">文件类型</label>
                    <select id="qr_type" name="qr_type" class="form-control">
                        <option value="png" selected>PNG格式图片</option>
                        <option value="eps">EPS 类型文件</option>
                        <option value="svg">SVG 类型文件</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="qr_size">尺寸</label>
                    <input type="text" class="form-control" name="qr_size" id="qr_size" placeholder="图片宽度" value="400">
                </div>
                <div class="form-group">
                    <label for="qr_margin">边距</label>
                    <input type="text" class="form-control" name="qr_margin" id="qr_margin" placeholder="边距" value="2">
                </div>
                <div class="form-group">
                    <label for="qr_color">颜色</label>
                    <input type="text" class="form-control" name="qr_color" id="qr_color" placeholder="颜色" value="000000">
                </div>
                <div class="form-group">
                    <label for="qr_bgcolor">背景颜色</label>
                    <input type="text" class="form-control" name="qr_bgcolor" id="qr_bgcolor" placeholder="颜色" value="FFFFFF">
                </div>
                <div class="form-group">
                    <label for="qr_error">容错级别</label>
                    <select id="qr_error" name="qr_error" class="form-control">
                        <option value="L">7% 的字节码恢复率.</option>
                        <option value="M">15% 的字节码恢复率.</option>
                        <option value="Q">25% 的字节码恢复率.</option>
                        <option value="H" selected>30% 的字节码恢复率.</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">下载二维码</button>
                </div>
            </form>

        </div>
    </div>

<?php } ?>
