<?php
$this->pageTitleBar('Departments');

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/dept', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw" ></i> New Department</a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Department name</th>
                <th>Created</th>
                <th>Members</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($rows as $dept) { ?>

                <tr valign="middle">
                    <td><?php echo $dept->getDeptId(); ?></td>
                    <td><?php echo $dept->getDeptName(); ?></td>
                    <td><?php echo $dept->getDeptCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td><?php echo $dept->getDeptMembers(); ?></td>
                    <td><?php echo $dept->getDeptStatusAsString(); ?></td>
                    <td>
                        <?php if($dept->getDeptId() > 1) { ?>
                        <a class="btn btn-info btn-xs" href="<?php echo $this->url('admin/dept_opt', ['action' => 'edit', 'key' => $dept->getDeptId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                            <?php if(!$dept->getDeptStatus()) { ?>
                                <a class="btn btn-success btn-xs" href="<?php echo $this->url('admin/dept_opt', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                    <span class="glyphicon glyphicon-ok"></span> Open
                                </a>
                            <?php } else { ?>
                                <a class="btn btn-danger btn-xs" href="<?php echo $this->url('admin/dept_opt', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Close
                                </a>
                            <?php } ?>
                            <a class="btn btn-info btn-xs" href="#">
                                <span class="glyphicon glyphicon-user"></span> Members
                            </a>
                        <?php } ?>
                    </td>
                </tr>

            <?php } ?>

        </table>



    </div>
</div>