<?php
$this->pageTitleBar('部门列表');

$this->sideTreeMenu()->setActiveId($activeId);


$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
   $("#pageModal").on("loaded.bs.modal", function (e) {
       //console.log(e.data);
   });

   // clean modal data force every time load newest data from server.
   $("#pageModal").on("hidden.bs.modal", function() {
      $(this).removeData("bs.modal");
   });

   $("body").on("click", "#save-dept-member", function () {
       var url = $(this).attr("path");
       var _target = $(this);

       var member_ids = new Array();
       $("#member-department-container").find("input[type='checkbox']").each(function () {
          if (this.checked) {
              member_ids.push(this.value);
          }
       });

       $(this).attr("disabled", true);
       $.post(url, {"selected": member_ids}, function (dt) {
            if (dt.success) {
               console.log(dt);
                $("#pageModal").modal('hide');
                document.location.reload();
                //$("#pageModal").removeData("bs.modal");
            } else {
                alert("Save changes failed, Please try again!");
                _target.removeAttr("disabled");
            }
       }, 'json');

   });
});

JS;
$this->inlineScript()->captureEnd();

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/dept', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw" ></i> 新增部门</a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>No</th>
                <th>分组名称</th>
                <th>创建时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>

            <?php $i = 1; foreach ($rows as $dept) { if($dept->getDeptId() == \Admin\Entity\Department::DEFAULT_DEPT_ID) { continue;} ?>

                <tr>
                    <td><?php echo $i++; ?></td>
                    <td><?php echo $dept->getDeptName(); ?></td>
                    <td><?php echo $dept->getDeptCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td>
                        <span class="label label-<?php echo \Admin\Entity\Department::STATUS_VALID == $dept->getDeptStatus() ? 'success' : 'danger'; ?>">
                            <?php echo $dept->getDeptStatusAsString(); ?>
                        </span>
                    </td>
                    <td>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    操作选项 <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php if (\Admin\Entity\Department::STATUS_VALID != $dept->getDeptStatus()) { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/dept', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                                <i class="fa fa-check fa-fw" aria-hidden="true"></i> 启用部门
                                            </a>
                                        </li>

                                    <?php } else { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/dept', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> 关闭部门
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/dept', ['action' => 'edit', 'key' => $dept->getDeptId()]); ?>">
                                                <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> 修改信息
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/message', ['action' => 'dept', 'key' => $dept->getDeptId()]); ?>">
                                                <i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i> 群发消息
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/dept', ['action' => 'members', 'key' => $dept->getDeptId()]); ?>" data-toggle="modal" data-target="#pageModal">
                                                <i class="fa fa-users fa-fw" aria-hidden="true"></i> 部门成员管理
                                            </a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>

            <?php } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>