<?php
$this->pageTitleBar('Departments');

$this->sideTreeMenu()->setActiveId('dept_list');

$this->headScript()->appendFile($this->basePath('js/admin/department.index.js'));

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/dept', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw" ></i> New Department</a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Department name</th>
                <th>Created</th>
                <th>Members</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($rows as $dept) { ?>

                <tr>
                    <td><?php echo $dept->getDeptId(); ?></td>
                    <td><?php echo $dept->getDeptName(); ?></td>
                    <td><?php echo $dept->getDeptCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td><?php echo $dept->getDeptMembers(); ?></td>
                    <td><?php echo $dept->getDeptStatusAsString(); ?></td>
                    <td>
                        <?php if($dept->getDeptId() > 1) { ?>
                            <ul class="nav nav-pills actions-list" role="tablist">
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        Actions <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <?php if (\Admin\Entity\Department::STATUS_VALID != $dept->getDeptStatus()) { ?>
                                            <li>
                                                <a href="<?php echo $this->url('admin/dept', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                                    <i class="fa fa-check fa-fw" aria-hidden="true"></i> Open
                                                </a>
                                            </li>

                                        <?php } else { ?>
                                            <li>
                                                <a href="<?php echo $this->url('admin/dept', ['action' => 'status', 'key' => $dept->getDeptId()]); ?>">
                                                    <i class="fa fa-times fa-fw" aria-hidden="true"></i> Close
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url('admin/dept', ['action' => 'edit', 'key' => $dept->getDeptId()]); ?>">
                                                    <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> Edit
                                                </a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="<?php echo $this->url('admin/dmr', ['action' => 'department-members', 'key' => $dept->getDeptId()]); ?>" data-toggle="modal" data-target="#pageModal">
                                                    <i class="fa fa-users fa-fw" aria-hidden="true"></i> Members
                                                </a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </li>
                            </ul>
                        <?php } else { ?>
                            <ul class="nav nav-pills actions-list" role="tablist"><li><a>&nbsp;</a></li></ul>
                        <?php } ?>
                    </td>
                </tr>

            <?php } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>