<?php
$this->pageTitleBar('添加一个客户端');
$this->sideTreeMenu()->setActiveId($activeId);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '客户端名称'
]);

$form->get('domain')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '例如: example.com'
]);

$form->get('ip')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '例如: 114.114.114.114'
]);

$form->get('active')->setAttributes([
    'type' => 'date',
    'class' => 'form-control',
]);

$form->get('expire')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'), '设置客户端名称'); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('domain'), '允许来访的域名'); ?>
            <?php echo $this->formElement($form->get('domain')); ?>
            <p class="text-muted">
                <small>域名格式: <strong>www.example.com</strong> 或者 <strong>example.com</strong></small>
            </p>
            <?php echo $this->formElementErrors($form->get('domain')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('ip'), '允许来访的IP地址'); ?>
            <?php echo $this->formElement($form->get('ip')); ?>
            <p class="text-muted">
                <small>IP 地址格式: <strong>xxx.xxx.xxx.xxx</strong>
            </p>
            <?php echo $this->formElementErrors($form->get('ip')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('active'), '允许客户端访问的开始时间'); ?>
            <?php echo $this->formElement($form->get('active')); ?>
            <?php echo $this->formElementErrors($form->get('active')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('expire'), '允许客户端访问的结束时间'); ?>
            <?php echo $this->formElement($form->get('expire')); ?>
            <?php echo $this->formElementErrors($form->get('expire')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
