<?php
$this->pageTitleBar('更新公众号信息');
$this->sideTreeMenu()->setActiveId($activeId);

$isIncludeAppId = \Admin\Entity\Wechat::STATUS_CHECKED != $wechat->getWxChecked();

if ($isIncludeAppId) {
    $form->get('appid')->setAttributes([
        'class' => 'form-control',
        'placeholder' => '这里请填写 AppID'
    ]);
}

$form->get('appsecret')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '这里请填写 AppSecret'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <?php if($isIncludeAppId) { ?>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('appid'), '微信公众号 AppID'); ?>
            <?php echo $this->formElement($form->get('appid')); ?>
            <?php echo $this->formElementErrors($form->get('appid')); ?>
        </div>
        <?php } ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('appsecret'), '微信公众号 AppSecret'); ?>
            <?php echo $this->formElement($form->get('appsecret')); ?>
            <?php echo $this->formElementErrors($form->get('appsecret')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
