<?php
$this->pageTitleBar('公众号管理');
$this->sideTreeMenu()->setActiveId($activeId);

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (!$wechat instanceof \Admin\Entity\Wechat) { ?>
        <p>
            <span>您还没有创建您的微信公众号, 是否需要现在创建? </span>
            <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/wechat', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw" ></i> 添加公众号</a>
        </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-8">
                    <p>AppID: <?php echo $wechat->getWxAppId(); ?></p>
                    <p>AppID: <?php echo $wechat->getWxAppSecret(); ?></p>
                </div>
                <div class="col-lg-2">
                    <p>允许状态</p>
                    <p>正常</p>
                </div>
                <div class="col-lg-2">
                    <p>验证状态</p>
                    <p>未验证</p>
                </div>
            </div>
            <hr>

        <?php } ?>
    </div>
</div>
