<?php
$this->pageTitleBar('公众号二维码管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/wechat.index.js'));

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (!$wechat instanceof \Admin\Entity\Wechat || $wechat->getQrcodes()->count() < 1) { ?>
            <p>
                <span>未发现您之前有生成二维码, 是否需要现在申请? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/wechat', ['action'=>'qrcodeadd']); ?>"><i class="fa fa-plus fa-fw" ></i> 申请二维码</a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/wechat', ['action'=>'addclient']); ?>"><i class="fa fa-plus fa-fw" ></i> 添加公众号客户端</a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th>客户端</th>
                            <th>生效时间</th>
                            <th>失效时间</th>
                            <th>访问控制(允许的域名及 IP)</th>
                            <th>操作</th>
                        </tr>
                        <?php
                        $clients = $wechat->getClients();
                        foreach ($clients as $client) {
                            if ($client instanceof \Admin\Entity\WechatClient) {
                        ?>
                        <tr>
                            <td><?php echo $client->getName(); ?></td>
                            <td><?php echo date('Y-m-d', $client->getActiveTime()); ?></td>
                            <td><?php echo date('Y-m-d', $client->getExpireTime()); ?></td>
                            <td>
                                域名: <?php echo $client->getDomain();  ?><br>
                                IP: <?php echo $client->getIp(); ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('admin/wechat', ['action' => 'editclient', 'key' => $client->getId()]); ?>">修改</a>
                                <span> | </span>
                                <a class="remove-client" href="<?php echo $this->url('admin/wechat', ['action' => 'remove', 'key' => $client->getId()]); ?>">删除</a>
                            </td>
                        </tr>
                        <?php } } ?>

                    </table>

                </div>
            </div>

        <?php } ?>
    </div>
</div>

