<?php
$this->pageTitleBar('公众号二维码管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/wechat.index.js'));

?>


<div class="row">
    <div class="col-lg-12">
        <?php if (!$wechat instanceof \Admin\Entity\Wechat || $wechat->getQrcodes()->count() < 1) { ?>
            <p>
                <span>未发现您之前有生成二维码, 是否需要现在申请? </span>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url('admin/wechat', ['action'=>'qrcodeadd']); ?>"><i class="fa fa-plus fa-fw" ></i> 申请二维码</a>
            </p>
        <?php } else { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/wechat', ['action'=>'qrcodeadd']); ?>"><i class="fa fa-plus fa-fw" ></i> 申请二维码</a>
                    </p>
                    <table class="table table-striped">
                        <tr>
                            <th>二维码</th>
                            <th>创建时间</th>
                            <th>失效时间</th>
                            <th>操作</th>
                        </tr>
                        <?php
                        $qrcodes = $wechat->getQrcodes();
                        foreach ($qrcodes as $qrcode) {
                            if ($qrcode instanceof \Admin\Entity\WechatQrcode) {
                        ?>
                        <tr>
                            <td><i class="fa fa-qrcode fa-fw"></i><?php echo $qrcode->getName(); ?></td>
                            <td><?php echo $qrcode->getCreated()->format('Y-m-d H:i:s'); ?></td>
                            <td>
                                <?php
                                $forever = '永久';
                                if (\Admin\Entity\WechatQrcode::TYPE_TEMP == $qrcode->getType()) {
                                    $expired = date('Y-m-d H:i:s', $qrcode->getExpired());
                                } else {
                                    $expired = $forever;
                                }
                                echo $expired;
                                ?>
                            </td>
                            <td>
                                <?php if($forever == $expired || $qrcode->getExpired() > time()) { ?>
                                <a href="<?php echo $this->url('admin/wechat', ['action' => 'qrcodedown', 'key' => $qrcode->getId()]); ?>">下载</a>
                                <span> | </span>
                                <?php } ?>
                                <a class="remove-qrcode" href="<?php echo $this->url('admin/wechat', ['action' => 'qrcoderemove', 'key' => $qrcode->getId()]); ?>">删除</a>
                            </td>
                        </tr>
                        <?php } } ?>

                    </table>

                </div>
            </div>

        <?php } ?>
    </div>
</div>

