<?php
$this->pageTitleBar('创建新成员');
$this->sideTreeMenu()->setActiveId($activeId);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '成员登入账号(E-mail)'
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '成员名称'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'), '设定登入账号(E-mail)'); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password'), '设定登入密码'); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'), '成员名字'); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>


    </div>
</div>
