<?php
$this->pageTitleBar('设置成员过期时间');
$this->sideTreeMenu()->setActiveId($activeId);


if(!$member instanceof \Admin\Entity\Member) {
    throw new \Admin\Exception\InvalidArgumentException('无效的用户信息');
}


$form->get('expired')->setAttributes([
    'class' => 'form-control',
    'value' => $member->getMemberExpired()->format('Y-m-d'),
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('expired'), '设定账号过期时间'); ?>
            <?php echo $this->formElement($form->get('expired')); ?>
            <?php echo $this->formElementErrors($form->get('expired')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
