<?php
$this->pageTitleBar('Administrator');

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/member', ['action'=>'add']); ?>"><i class="fa fa-plus fa-fw" ></i> New Administrator</a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Administrator</th>
                <th>E-mail Address</th>
                <th>Date Created</th>
                <th>Level</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($rows as $member) { ?>

                <tr valign="middle">
                    <td><?php echo $member->getMemberId(); ?></td>
                    <td><?php echo $member->getMemberName(); ?></td>
                    <td><?php echo $member->getMemberEmail(); ?></td>
                    <td><?php echo $member->getMemberCreated(); ?></td>
                    <td><?php echo $member->getMemberLevelAsString(); ?></td>
                    <td><?php echo $member->getMemberStatusAsString(); ?></td>
                    <td>
                        <?php if($member->getMemberId() > 1) { ?>
                            <a class="btn btn-info btn-xs" href="<?php echo $this->url('admin/member_opt', ['action' => 'edit', 'key' => $member->getMemberId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </a>
                            <a class="btn btn-info btn-xs" href="<?php echo $this->url('admin/member_opt', ['action' => 'status', 'key' => $member->getMemberId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Status
                            </a>
                            <a class="btn btn-info btn-xs" href="<?php echo $this->url('admin/member_opt', ['action' => 'level', 'key' => $member->getMemberId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Level
                            </a>
                            <a class="btn btn-info btn-xs" href="<?php echo $this->url('admin/member_opt', ['action' => 'password', 'key' => $member->getMemberId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Password
                            </a>
                        <?php } ?>
                    </td>
                </tr>

            <?php } ?>

        </table>


    </div>
</div>