<?php
$this->pageTitleBar('成员管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/member.index.js'));

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/member', ['action'=>'add']); ?>">
                <i class="fa fa-plus fa-fw" ></i> 添加成员
            </a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>No</th>
                <th>名字</th>
                <th>登录账号</th>
                <th>过期时间</th>
                <th>等级</th>
                <th>状态</th>
                <th>操作</th>
            </tr>

            <?php $i = 1; foreach ($rows as $member) { if($member->getMemberId() == \Admin\Entity\Member::DEFAULT_MEMBER_ID) {continue;} ?>

                <tr>
                    <td><?php echo $i++; ?></td>
                    <td><?php echo $member->getMemberName(); ?></td>
                    <td><?php echo $member->getMemberEmail(); ?></td>
                    <td><?php echo $member->getMemberExpired()->format('Y-m-d'); ?></td>
                    <td><?php echo $member->getMemberLevelAsString(); ?></td>
                    <td>
                        <span class="label label-<?php echo \Admin\Entity\Member::STATUS_ACTIVATED == $member->getMemberStatus() ? 'success' : 'danger'; ?>">
                            <?php echo $member->getMemberStatusAsString(); ?>
                        </span>
                    </td>
                    <td>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    操作选项 <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php if(\Admin\Entity\Member::STATUS_ACTIVATED != $member->getMemberStatus()) { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'status', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-check fa-fw" aria-hidden="true"></i> 激活账户
                                            </a>
                                        </li>
                                    <?php } else { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'status', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> 锁定账户
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'edit', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> 修改信息
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'level', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-level-up fa-fw" aria-hidden="true"></i> 更新等级
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'password', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-hashtag fa-fw" aria-hidden="true"></i> 更新密码
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'expired', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-calendar-check-o fa-fw" aria-hidden="true"></i> 过期时间
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/message', ['action' => 'send', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i> 发送消息
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'departments', 'key' => $member->getMemberId()]); ?>" data-toggle="modal" data-target="#pageModal">
                                                <i class="fa fa-users fa-fw" aria-hidden="true"></i> 成员部门管理
                                            </a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>

            <?php } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>

