<?php
$this->pageTitleBar('成员管理');
$this->sideTreeMenu()->setActiveId($activeId);

$this->headScript()->appendFile($this->basePath('js/admin/member.index.js'));

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/member', ['action'=>'add']); ?>">
                <i class="fa fa-plus fa-fw" ></i> 添加成员
            </a>
        </p>

        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>名字</th>
                <th>登录账号</th>
                <th>创建时间</th>
                <th>等级</th>
                <th>状态</th>
                <th>操作</th>
            </tr>

            <?php foreach ($rows as $member) { ?>

                <tr>
                    <td><?php echo $member->getMemberId(); ?></td>
                    <td><?php echo $member->getMemberName(); ?></td>
                    <td><?php echo $member->getMemberEmail(); ?></td>
                    <td><?php echo $member->getMemberCreated()->format('Y-m-d H:i:s'); ?></td>
                    <td><?php echo $member->getMemberLevelAsString(); ?></td>
                    <td><?php echo $member->getMemberStatusAsString(); ?></td>
                    <td>
                        <?php if($member->getMemberId() > 1) { ?>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Actions <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php if(\Admin\Entity\Member::STATUS_ACTIVATED != $member->getMemberStatus()) { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'status', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-check fa-fw" aria-hidden="true"></i> Activate
                                            </a>
                                        </li>
                                    <?php } else { ?>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'status', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> Retried
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'edit', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> Edit
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'level', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-level-up fa-fw" aria-hidden="true"></i> Level
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/member', ['action' => 'password', 'key' => $member->getMemberId()]); ?>">
                                                <i class="fa fa-hashtag fa-fw" aria-hidden="true"></i> Password
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/dmr', ['action' => 'member-departments', 'key' => $member->getMemberId()]); ?>" data-toggle="modal" data-target="#pageModal">
                                                <i class="fa fa-users fa-fw" aria-hidden="true"></i> Departments
                                            </a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        </ul>
                        <?php } else { ?>
                            <ul class="nav nav-pills actions-list" role="tablist"><li><a>&nbsp;</a></li></ul>
                        <?php } ?>
                    </td>
                </tr>

            <?php } ?>

        </table>

    </div>
</div>

<?php echo $this->pagination()->render(); ?>

