<?php
$this->pageTitleBar('成员等级更新');

$this->sideTreeMenu()->setActiveId($activeId);

if(!$member instanceof \Admin\Entity\Member) {
    throw new \Admin\Exception\InvalidArgumentException('无效的用户信息');
}


$form->get('level')->setAttributes([
    'class' => 'form-control',
    'value' => $member->getMemberLevel(),
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('level'), '帐号等级'); ?>
            <?php echo $this->formElement($form->get('level')); ?>
            <?php echo $this->formElementErrors($form->get('level')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
