<?php
$this->pageTitleBar('Add new administrator');
$this->sideTreeMenu()->setActiveId($activeId);

$form->get('password')->setAttributes([
    'class' => 'form-control',
])->setOptions([
    'label' => 'Administrator new password',
]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<p class="text-danger">');
$helper->setMessageSeparatorString('</p><p class="text-danger">');
$helper->setMessageCloseString('</p>');

$form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
