<?php
$this->headTitle('登入系统');

// 表单: 帐号
$input = $form->get('email');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '登录账户不能留空, 请输入您的账号.',
    '__undefined__' => '请使用正确的 E-mail 邮箱地址.',
]);


// 表单: 密码
$input = $form->get('password');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'在这里输入您的登录密码',
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '登录密码不能为空, 请输入您的密码.',
    \Zend\Validator\StringLength::TOO_SHORT => '登录密码长度太短了.',
    \Zend\Validator\StringLength::TOO_LONG => '登录密码长度太长了.',
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => '登入系统']);

$form->prepare();

?>

<div id="centered_container" class="centered">
    <div class="login-container">
        <h3 class="text-center">登入管理系统</h3>

        <?php if(1 != $login_code) { ?>
        <div class="alert alert-warning" role="alert">
            <?php if(-1 == $login_code) { ?>
            <strong>警告!</strong> 登入账户( E-Mail) 地址无效.
            <?php } ?>
            <?php if(-4 == $login_code) { ?>
                <strong>警告!</strong> 该账号目前被锁定, 暂不允许登入.
            <?php } ?>
            <?php if(-3 == $login_code) { ?>
                <strong>警告!</strong> 请使用正确的账号和密码登入.
            <?php } ?>
            <?php if(0 == $login_code) { ?>
                <strong>警告!</strong> 您的账号已经过期, 禁止登入!
            <?php } ?>
        </div>
        <?php } ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'), '登录账户'); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password'), '登录密码'); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>