<?php
$this->headTitle('登入系统');

$form = $this->form;

$input = $form->get('email');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if ($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '登录账户不能留空, 请输入您的账号.';
            unset($inputMessages[$key]);
            continue;
        }

        if (in_array($key, [
            \Zend\Validator\EmailAddress::INVALID,
            \Zend\Validator\EmailAddress::INVALID_FORMAT,
            \Zend\Validator\EmailAddress::INVALID_HOSTNAME,
            \Zend\Validator\EmailAddress::INVALID_MX_RECORD,
            \Zend\Validator\EmailAddress::INVALID_SEGMENT,
            \Zend\Validator\EmailAddress::DOT_ATOM,
            \Zend\Validator\EmailAddress::QUOTED_STRING,
            \Zend\Validator\EmailAddress::INVALID_LOCAL_PART,
            \Zend\Validator\EmailAddress::LENGTH_EXCEEDED,
            \Zend\Validator\EmailAddress::INVALID,
            \Zend\Validator\Hostname::INVALID,
            \Zend\Validator\Hostname::CANNOT_DECODE_PUNYCODE,
            \Zend\Validator\Hostname::INVALID_DASH,
            \Zend\Validator\Hostname::INVALID_HOSTNAME,
            \Zend\Validator\Hostname::INVALID_HOSTNAME_SCHEMA,
            \Zend\Validator\Hostname::INVALID_LOCAL_NAME,
            \Zend\Validator\Hostname::INVALID_URI,
            \Zend\Validator\Hostname::IP_ADDRESS_NOT_ALLOWED,
            \Zend\Validator\Hostname::LOCAL_NAME_NOT_ALLOWED,
            \Zend\Validator\Hostname::UNDECIPHERABLE_TLD,
            \Zend\Validator\Hostname::UNKNOWN_TLD,
        ])) {
            $localMessages[\Zend\Validator\EmailAddress::INVALID_FORMAT] = '请使用正确的 E-mail 邮箱地址.';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}

// 表单: 密码
$input = $form->get('password');
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'在这里输入您的登录密码',
]);

$inputMessages = $input->getMessages();
$localMessages = [];
if(!empty($inputMessages)) {
    $keys = array_keys($inputMessages);
    foreach ($keys as $key) {
        if($key == \Zend\Validator\NotEmpty::IS_EMPTY) {
            $localMessages[$key] = '登录密码不能为空, 请输入您的密码.';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_SHORT) {
            $localMessages[$key] = '登录密码长度太短了.';
            unset($inputMessages[$key]);
            continue;
        }
        if ($key == \Zend\Validator\StringLength::TOO_LONG) {
            $localMessages[$key] = '登录密码长度太长了.';
            unset($inputMessages[$key]);
            continue;
        }
    }
}
//var_dump($inputMessages);
if (!empty($localMessages)) {
    $input->setMessages(array_merge($inputMessages, $localMessages));
}

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => '登入系统']);

$form->prepare();

?>

<div id="centered_container" class="centered">
    <div class="login-container">
        <h3 class="text-center">登入管理系统</h3>

        <?php if(1 != $login_code) { ?>
        <div class="alert alert-warning" role="alert">
            <?php if(-1 == $login_code) { ?>
            <strong>警告!</strong> 登入账户( E-Mail) 地址无效.
            <?php } ?>
            <?php if(-4 == $login_code) { ?>
                <strong>警告!</strong> 该账号目前被锁定, 暂不允许登入.
            <?php } ?>
            <?php if(-3 == $login_code) { ?>
                <strong>警告!</strong> 请使用正确的账号和密码登入.
            <?php } ?>
            <?php if(0 == $login_code) { ?>
                <strong>警告!</strong> 您的账号已经过期, 禁止登入!
            <?php } ?>
        </div>
        <?php } ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'), '登录账户'); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password'), '登录密码'); ?>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>