<?php
$this->headTitle('微信接口文档');

$this->barMenu()->setActiveItemId('apidoc');

$this->barBreadcrumbs()->setItems([
    '微信接口服务' => $this->url('home'),
    '接口文档' => $this->url('app/index', ['action' => 'apidoc', 'suffix' => '.html']),
    "Version: 1.0" => '#'
]);

$this->headScript()->appendFile($this->basePath('open-source-assets/showdown-1.6.3/showdown.min.js'));


$this->inlineScript()->captureStart();
echo <<<JS
var converter = new showdown.Converter();
$("#apiHtml").html(converter.makeHtml($("#apiMd").val()));
JS;
$this->inlineScript()->captureEnd();

echo '<div class="row"><div class="col-lg-12"><div id="apiHtml"></div><textarea id="apiMd" style="display: none;">';
?>


> #### API 公用参数说明

`wxid`: 微信公众号编号, 整型数字. 比如: *1253*

`client`: 访问客户端识别码, 字符和数字的编码, 每个客户端唯一. 比如: *ufh8jk*

***

> #### API 接口访问控制.

API 访问控制分为四种模式.

`IP 限制`: *API 服务器检查调用该 API 的来源服务器的 IP 地址, 未在后台设定允许的 IP 地址将无法访问该 API.*

`域名限制`: *部分 API 需要包含相关域名的, 比如 JSSDK 签名 API, 如果域名未在后台指定, 则无法使用该 API.*

`时效限制`: *后台对每个客户端都有时效设定, 超出时效的客户端无法访问任何 API.*

`接口限制`: *后台对每个客户端单独配置可用接口清单, 客户端无法访问在其清单之外的 API.*

*具体的客户端配置信息请联系公众号管理员确认.*

***



> #### API: 网页授权接口

接口地址: `http://www.bentuzi.com/weixin/oauth/[wxid]/[client].html?type=base|userinfo&url=urlencode('http://www.example.com/demo.html')`

接口说明: 通用型微信公众号授权接口, 通过该接口可以同时接入不同的微信网页并且获得当前用的信息.

访问控制: `域名限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
// File: /get_user_oauth.php

// ... other code

header('Location: http://www.bentuzi.com/weixin/oauth/2354/uk3t5x.html?type=userinfo&url=' . urlencode('http://www.example.com/demo.html'));
exit;

```

参数说明

* `type`: 授权类型, userinfo: 显示授权, 需要用户手动确认, base: 隐式授权. 不显示授权界面.
* `url`: 授权完成回调的地址, 使用 urlencode 编码.


授权完成参数注入回调URL:
```
// type为: base
http://www.example.com/demo.html?openid=OPENID

// type为: userinfo
http://www.example.com/demo.html?openid=OPENID&nickname=NICKNAME&sex=SEX&headimgurl=HEADIMGURL&province=PROVINCE&city=CITY&country=COUNTRY
```

***



> #### API: 获取JSSDK签名授权

接口地址: `http://www.bentuzi.com/weixin/jssign/[wxid]/[client].json?url=URL`

接口说明: 通用型微信公众号签名接口, 通过该接口可以使用微信的 JSSDK 完成自定义分享, 文件上传等众多接口功能.

访问控制: `IP 限制`, `域名限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
$res = file_get_contents('http://www.bentuzi.com/weixin/jssign/2354/uk3t5x.json?url=' . urlencode('http://www.example.com/demo.html'));
print_r(json_decode($res,true));

// 正确结果
{
    "success": true,
    "appId: "wx AppID"
    "timestamp": "1492268823",
    "nonceStr": "nonce_string",
    "signature": "SIGNATURE",
    "rawString": "SIGNATURE_SEED",
    "url": "http://www.example.com/demo.html"
}

// 异常结果
{
    "success": false,
    "errcode": 9999,
    "errmsg": "ERROR_MESSAGE"
}

```

***




> #### API: 获取 AccessToken

接口地址: `http://www.bentuzi.com/weixin/accesstoken/[wxid]/[client].json`

接口说明: 该接口危险性较高. 请勿随意分配给客户端. 客户端通过 AccessToken 可以提取公众平台各种信息.

访问控制: `IP 限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
$res = file_get_contents('http://www.bentuzi.com/weixin/accesstoken/2354/uk3t5x.json');
print_r(json_decode($res,true));

// 正确结果
{
    "success": true,
    "access_token": "ACCESS_TOKEN_VALUE"
}

// 异常结果
{
    "success": false,
    "errcode": 9999,
    "errmsg": "ERROR_MESSAGE"
}

```

***




> #### API: 获取 JsApiTicket

接口地址: `http://www.bentuzi.com/weixin/jsapiticket/[wxid]/[client].json`

接口说明: 提取微信 JSSDK 的 Ticket 接口, 客户端可以通过该 Ticket 自己完成 JS 签名等工作.

访问控制: `IP 限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
$res = file_get_contents('http://www.bentuzi.com/weixin/jsapiticket/2354/uk3t5x.json');
print_r(json_decode($res,true));

// 正确结果
{
    "success": true,
    "jsapi_ticket": "JS_API_TICKET_VALUE"
}

// 异常结果
{
    "success": false,
    "errcode": 9999,
    "errmsg": "ERROR_MESSAGE"
}

```

***





> #### API: 获取 ApiTicket

接口地址: `http://www.bentuzi.com/weixin/apiticket/[wxid]/[client].json`

接口说明: 使用该接口的 Ticket 可以完成制作 卡券 等业务签名.

访问控制: `IP 限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
$res = file_get_contents('http://www.bentuzi.com/weixin/apiticket/2354/uk3t5x.json');
print_r(json_decode($res,true));

// 正确结果
{
    "success": true,
    "api_ticket": "API_TICKET_VALUE"
}

// 异常结果
{
    "success": false,
    "errcode": 9999,
    "errmsg": "ERROR_MESSAGE"
}

```

***





> #### API: 获取用户信息

接口地址: `http://www.bentuzi.com/weixin/userinfo/[wxid]/[client].json?openid=OPENID`

接口说明: 使用该接口可以根据 OpenID 提取用户信息, 也可以通过该接口查询该OpenID 的用户是否是公众号粉丝.

访问控制: `IP 限制`, `时效限制`, `接口限制`


```
// PHP 示例代码
$res = file_get_contents('http://www.bentuzi.com/weixin/userinfo/2354/uk3t5x.json?openid=o6_bmjrPTlm6_2sgVt7hMZOPfL2M');
print_r(json_decode($res,true));

// 正确结果
{
    "success": true,
    "userinfo": {
        "subscribe": 1,
        "openid": "o6_bmjrPTlm6_2sgVt7hMZOPfL2M",
        ...
    }
}

// 异常结果
{
    "success": false,
    "errcode": 9999,
    "errmsg": "ERROR_MESSAGE"
}

```




<?php echo '</textarea></div></div>'; ?>
