<?php
$this->headTitle('申请试用');

$this->barMenu()->setActiveItemId(null);

$this->barBreadcrumbs()->setItems([
    'Bentuzi' => $this->url('home'),
    '服务&产品' => $this->url('service'),
    '申请试用' => $this->url('apply'),
]);


$form = $this->form;

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'您的名字'
]);
$form->get('appid')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'微信公众号 AppID'
]);
$form->get('appsecret')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'微信公众号 AppSecret'
]);
$form->get('captcha')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-primary',
    'value' => '现在申请',
]);

$form->prepare();


$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    $("form").submit(function () {
        var appid = $("#appid").val();
        if(appid.length < 3) {
            $("#appid").focus();
            return false;
        }
        var appsecret = $("#appsecret").val();
        if(appsecret.length < 3) {
            $("#appsecret").focus();
            return false;
        }
        if(confirm("请确认您的公众号的相关信息为:\\nAppID: " + appid + "\\nAppSecret: " + appsecret + "\\n接下来系统将和微信平台确认此 ID, 一旦确认 AppID 有效, 我们将给您发送正式试用邮件. \\n是否需要继续?")) {
            alert("接下来和微信平台进行信息验证, 可能需要一点时间, 请勿离开此页, 我们会通知您验证结果.");
            $(":submit", this).attr("disabled","disabled");
            return true;
        } else {
            return false;
        }
    });
});
JS;
$this->inlineScript()->captureEnd();


?>

<div class="row">
    <div class="col-lg-5">
        <h3>申请试用</h3>
        <p>请填写下面的表单, 系统会给您发送申请激活邮件. 请注意查收邮件.</p>
        <?php if(!empty($error) && 'wx' == $error) { ?>
            <div class="alert alert-danger">
                <strong>公众号未能通过微信平台确认, 请确认的公众号信息填写正确.</strong>
            </div>
        <?php } ?>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'), '您的邮件地址'); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'), '告诉我们您的名字'); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('appid'), '微信公众号 AppID'); ?>
            <?php echo $this->formElement($form->get('appid')); ?>
            <?php echo $this->formElementErrors($form->get('appid')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('appsecret'), '微信公众号 AppSecret'); ?>
            <?php echo $this->formElement($form->get('appsecret')); ?>
            <?php echo $this->formElementErrors($form->get('appsecret')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('captcha')); ?>
            <p class="hint small text-muted">为防止垃圾信息, 请您输入信息确认码. 谢谢!</p>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
