<?php
$this->headTitle('联络我们');
$this->barMenu()->setActiveItemId('contact');
$this->barBreadcrumbs()->setItems([
    'Bentuzi' => $this->url('home'),
    '联络我们' => $this->url('contact'),
]);

$form = $this->form;

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);
$form->get('subject')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'请告诉我们您的目的'
]);
$form->get('message')->setAttributes([
    'class'=>'form-control',
    'rows'=>6,
    'placeholder'=>'请告诉我们您想联络的具体内容'
]);
$form->get('captcha')->setAttributes([
    'class' => 'form-control',
]);
$form->get('submit')->setAttributes([
    'class'=>'btn btn-primary',
    'value' => '发送信息',
]);

$form->prepare();

?>

<div class="row">
    <div class="col-lg-5">
        <h3>联络我们</h3>
        <p>与我们联系请填写下面的表单, 我们会第一时间与你反馈.</p>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email'), '您的邮件地址'); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('subject'), '联络主题'); ?>
            <?php echo $this->formElement($form->get('subject')); ?>
            <?php echo $this->formElementErrors($form->get('subject')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('message'), '具体内容'); ?>
            <?php echo $this->formElement($form->get('message')); ?>
            <?php echo $this->formElementErrors($form->get('message')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('captcha')); ?>
            <p class="hint small text-muted">为防止垃圾信息, 请您输入信息确认码. 谢谢!</p>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
    <div class="col-lg-5 col-lg-offset-2">
        <h3>关于我们</h3>
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">Who?</h4>
                <p>宽绩网络科技是一家专门从事互联网行业的软件平台服务供应商, 由技术实力强大的的 Bentuzi 团队提供技术支持.</p>
            </div>
        </div>

        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">What?</h4>
                <p>
                    我们专注于互联网的技术开发, 方案提供及咨询服务. <br>
                    1. 微信二次开发技术服务及技术方案咨询服务.<br>
                    2. H5 产品开发服务.<br>
                    3. 轻量级的 App 开发及技术支持服务<br>
                    4. 定制化的 CMS 及 CRM 系统开发运维服务.
                </p>
            </div>
        </div>

        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">Why?</h4>
                <p>
                    我们希望帮助企业低成本的提高业务处理效率.<br>
                    1. 使用我们成熟的技术方案可以大大节约您的时间和成本 <br>
                    2. 专业的项目方案及系统设计让您在系统升级及功能扩展高枕无忧.<br>
                    3. 我们只专注做技术服务商, 术业有专攻.
                </p>
            </div>
        </div>
    </div>
</div>
