<?php
$this->barMenu()->setActiveItemId(null);


$this->inlineScript()->captureStart();
echo <<<JS
    $(function () {
       
       $(".test").click(function () {
           alert("start ajax call");
           $.get($(this).attr("href"), function (dt) {
               alert(dt);
           });
           $(this).blur();
           return false;
       });
       
       
    });
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('app/index', ['action' => 'test', 'suffix' => '.html']); ?>" class="test btn btn-default">Test Content</a>
    </div>

</div>

<h1 style="color: #FFFFFF"> ^o^ Oh!!!</h1>