<?php
$this->barMenu()->setActiveItemId(null);


$this->inlineScript()->captureStart();
echo <<<JS
    $(function () {

       
    });
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h3>微信接口服务</h3>
            <p>欢迎使用微信接口服务, 为了保障您的公众号信息及粉丝信息安全, 强烈推荐独立的微信公众号授权, 分享等接口服务.</p>
            <p>全面的独立接口和安全控制, 方便你精确控制每个供应商需要的不同接口及同时接入多家供应商的微信公众号的相关服务接入.</p>
            <p>抛弃臃肿无用的开源微信管理系统, 保持公众号的完全自主控制.</p>
            <p><a class="btn btn-primary btn-lg" href="<?php echo $this->url('service'); ?>" role="button">了解详情</a></p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">独立的微信中控服务器</div>
            <div class="panel-body">
                我们在实际的业务处理中, 经常遇到公众号同时开展多个 H5 活动的需求, 不同的供应商对授权, 分享等需求. 任何一家供应商主宰公众号的授权都导致大量的沟通工作. 在这里 ,您只需要给不同的供应商分配接口即可.
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">独立的接口授权服务</div>
            <div class="panel-body">
                我们的中控服务提供精确的控制服务, 从一个供应商的需要使用的接口时间及接口类型, 到供应商的请求来源 IP, 域名, 我们都可以完全进行控制. 排除匿名的访问读取读取公众号任何信息.
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">公众号菜单及二维码等服务</div>
            <div class="panel-body">
                除了核心的接口服务之外, 我们另外顺便针对使用频率高的公众号菜单及二维码提供可视化和定制化服务. 所有的操作均可以在控制中心轻松完成. 不需要您有任何技术基础均可熟练操作.
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12" style="height: 473px; background-image: url('/img/mp_wiki.jpg'); background-size: auto 473px; background-position: center center; background-repeat: no-repeat;">
    </div>
</div>

<div class="row">
    <div class="col-log-12">
        <h3 style="color: #fff;">^o^</h3>
    </div>
</div>