<?php

$this->headTitle("服务&产品");

$this->barMenu()->setActiveItemId('service');

//$this->barMenu()->setItems([]);

// Setting the breadcrumbs
$this->barBreadcrumbs()->setItems([
    'Bentuzi' => $this->url('home'),
    '服务&产品' => $this->url('service'),
]);
?>

<style>
    table > tbody > tr > td {
        vertical-align: middle !important;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered table-hover">
            <tr>
                <th width="50%">微信公众号服务</th>
                <th width="25%">共享版</th>
                <th width="25%">定制版</th>
            </tr>
            <tr>
                <td>
                    <strong>公众号接入</strong>
                    <br>
                    <small class="text-muted">微信公众账号接入平台</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>免费试用</strong>
                    <br>
                    <small class="text-muted">每个微信认证公众号可以申请7天免费体验服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>自定义菜单</strong>
                    <br>
                    <small class="text-muted">支持多套公众号自定义菜单及切换服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>个性化菜单</strong>
                    <br>
                    <small class="text-muted">支持多套公众号个性化菜单及切换服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口: AccessToken 共享服务</strong>
                    <br>
                    <small class="text-muted">集中管理 AccessToken 对外授权服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口: 用户资料读取服务</strong>
                    <br>
                    <small class="text-muted">统一关注粉丝的用户信息读取服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口: 用户认证服务</strong>
                    <br>
                    <small class="text-muted">集中提供网页用户授权服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口: 分享接口服务</strong>
                    <br>
                    <small class="text-muted">集中提供微信分享认证服务</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口安全服务</strong>
                    <br>
                    <small class="text-muted">针对每个授权客户进行安全过滤, 防止恶意调用接口.</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>二维码服务</strong>
                    <br>
                    <small class="text-muted">任意生成 png, svg, eps 格式的公众号带参二维码.</small>
                </td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>二维码追踪服务</strong>
                    <br>
                    <small class="text-muted">跟踪由本平台发行的公众号二维码被扫描数据统计</small>
                </td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>粉丝同步服务</strong>
                    <br>
                    <small class="text-muted">同步公众号订阅者数据</small>
                </td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>接口访问统计</strong>
                    <br>
                    <small class="text-muted">追踪授权出去的接口被调用数据统计</small>
                </td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>超大并发请求服务</strong>
                    <br>
                    <small class="text-muted">支持超大访问量的公众号接口调用</small>
                </td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>独享服务器服务</strong>
                    <br>
                    <small class="text-muted">支持公众号独立服务器部署支持</small>
                </td>
                <td><i class="fa fa-close fa-fw fa-2x text-danger" aria-hidden="true"></i></td>
                <td><i class="fa fa-check fa-fw fa-2x text-success" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>
                    <strong>服务费用</strong>
                    <br>
                    <small class="text-muted">服务提供最短时限为12个月</small>
                </td>
                <td>1000元/月</td>
                <td>按需求收费</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <a class="btn btn-success" href="<?php echo $this->url('apply'); ?>">现在申请试用</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->url('contact'); ?>">现在联络我们</a>
                </td>
            </tr>
        </table>
    </div>
</div>

