<?php

$this->headTitle("服务&产品");

$this->barMenu()->setActiveItemId('service');

//$this->barMenu()->setItems([]);

// Setting the breadcrumbs
$this->barBreadcrumbs()->setItems([
    'Bentuzi' => $this->url('home'),
    '服务&产品' => $this->url('service'),
]);
?>

<style>
    table > tbody > tr > td {
        vertical-align: middle !important;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered table-hover">
            <tr>
                <th width="50%">微信公众号服务</th>
                <th width="25%">共享版</th>
                <th width="25%">定制版</th>
            </tr>
            <?php foreach($items as $item) { ?>
                <tr>
                    <td>
                        <strong><?php echo $item['title']; ?></strong>
                        <br>
                        <small class="text-muted"><?php echo $item['desc']; ?></small>
                    </td>
                    <td><i class="fa fa-<?php echo 1==$item['share'] ? 'check' : 'close'; ?> fa-fw fa-2x text-<?php echo 1==$item['share'] ? 'success' : 'danger'; ?>" aria-hidden="true"></i></td>
                    <td><i class="fa fa-<?php echo 1==$item['pro'] ? 'check' : 'close'; ?> fa-fw fa-2x text-<?php echo 1==$item['pro'] ? 'success' : 'danger'; ?>" aria-hidden="true"></i></td>
                </tr>
            <?php } ?>
            <tr>
                <td>
                    <strong>服务费用</strong>
                    <br>
                    <small class="text-muted">服务提供最短时限为12个月</small>
                </td>
                <td>1000元/月</td>
                <td>按需求收费</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <a class="btn btn-success" href="<?php echo $this->url('apply'); ?>">现在申请试用</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->url('contact'); ?>">现在联络我们</a>
                </td>
            </tr>
        </table>
    </div>
</div>

