<?php
// Setting the active menu
$this->barMenu()->setActiveItemId('test');

// Setting the breadcrumbs
$this->barBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Test' => '',
]);


$form = $this->form;

$inputName = $form->get('name');
$messages = $inputName->getMessages();
if (!empty($messages)) {
    $localMessages = [];
    if (array_key_exists(\Zend\Validator\NotEmpty::IS_EMPTY, $messages)) {
        $localMessages[\Zend\Validator\NotEmpty::IS_EMPTY] = '不能为空空';
    }

    $inputName->setMessages(array_merge($messages, $localMessages));
}

var_dump($messages);


$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'您的名字'
]);


$form->get('submit')->setAttributes([
    'class'=>'btn btn-primary',
    'value' => '现在测试',
]);

$form->prepare();




?>
<h1>Test</h1>

<div class="row">
    <div class="col-lg-5">
        <h3>Test</h3>

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formElement($form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('name'), '告诉我们您的名字'); ?>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
