<?php
$this->pageTitleBar('确认订单付款');
$this->sideTreeMenu()->setActiveId($activeId);

if(!$order instanceof \WeChat\Entity\Order) {
    throw new \Admin\Exception\InvalidArgumentException('无效的参数');
}

$weChat = $order->getWeChat();
$member = $order->getWeChat()->getMember();

?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th colspan="2">订单信息</th>
            </tr>
            <tr>
                <td>订单编号:</td>
                <td><strong><?php echo $order->getNo(); ?></strong></td>
            </tr>
            <tr>
                <td>公众号:</td>
                <td><?php echo $weChat->getWxAppId(); ?></td>
            </tr>
            <tr>
                <td>管理者:</td>
                <td><?php echo $member->getMemberName(); ?></td>
            </tr>
            <tr>
                <td>管理帐号:</td>
                <td><?php echo $member->getMemberEmail(); ?></td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="text-center">
                        <form method="post">
                            <button type="submit" class="btn btn-success">确认已经付款到账</button>
                        </form>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
