<?php
$this->pageTitleBar('公众号列表');
$this->sideTreeMenu()->setActiveId($activeId);

?>

<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-striped">
                    <tr>
                        <th>公众号</th>
                        <th>过期时间</th>
                        <th>操作</th>
                    </tr>
                    <?php foreach ($rows as $row) { if ($row instanceof \WeChat\Entity\Account) { ?>
                        <tr>
                            <td><?php echo $row->getWxAppId(); ?></td>
                            <td><?php echo date('Y-m-d H:i:s', $row->getWxExpired()); ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/weChat', ['action' => 'expired', 'key' => $row->getWxId()]); ?>">
                                    设置过期时间
                                </a>
                            </td>
                        </tr>
                    <?php } } ?>

                </table>
            </div>
        </div>
    </div>
</div>

<?php echo $this->pagination()->render(); ?>

