<?php
$this->pageTitleBar('我的发票');
$this->sideTreeMenu()->setActiveId($activeId);

?>


<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-striped">
                    <tr>
                        <th width="25%">开票信息</th>
                        <th width="10%">金额(元)</th>
                        <th width="40%">邮递信息</th>
                        <th width="10%">状态</th>
                        <th width="15%">操作</th>
                    </tr>
                    <?php
                    foreach ($rows as $invoice) {
                        if ($invoice instanceof \WeChat\Entity\Invoice) {
                            $member = $invoice->getWeChat()->getMember();
                    ?>
                            <tr>
                                <td>
                                    抬头: <?php echo $invoice->getTitle(); ?>
                                    <br>
                                    申请人: <?php echo $member->getMemberName(); ?>
                                    <br>
                                    <small>帐号: <?php echo $member->getMemberEmail(); ?></small>
                                </td>
                                <td>&yen;<?php echo $invoice->getMoney(); ?></td>
                                <td>
                                    收件: <?php echo $invoice->getReceiver(); ?><br>
                                    电话: <?php echo $invoice->getPhone(); ?><br>
                                    <small>地址: <?php echo $invoice->getAddress(); ?></small><br>
                                </td>
                                <td>
                                    <button class="btn btn-<?php
                                    if(\WeChat\Entity\Invoice::STATUS_INVOICE_REFUSED == $invoice->getStatus()) {
                                        echo 'danger';
                                    } else if(\WeChat\Entity\Invoice::STATUS_INVOICE_PRINT == $invoice->getStatus() ||
                                        \WeChat\Entity\Invoice::STATUS_INVOICE_DELIVER == $invoice->getStatus()) {
                                        echo 'success';
                                    } else {
                                        echo 'default';
                                    }
                                    ?> btn-xs">
                                        <?php echo $invoice->getStatusAsString(); ?>
                                    </button>
                                </td>
                                <td>
                                    <?php if($invoice->getStatus() != \WeChat\Entity\Invoice::STATUS_INVOICE_REFUSED) { ?>
                                    <a class="btn btn-warning btn-xs" href="<?php echo $this->url('admin/weChat', ['action' => 'update-invoice', 'key' => $invoice->getId()]); ?>">更新状态</a>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } } ?>

                </table>

            </div>
        </div>
    </div>
</div>


<?php echo $this->pagination()->render(); ?>