<?php
$this->pageTitleBar('更新发票状态');
$this->sideTreeMenu()->setActiveId($activeId);

if(!$invoice instanceof \WeChat\Entity\Invoice) {
    throw new \Admin\Exception\InvalidArgumentException('无效的参数');
}

$member = $invoice->getWeChat()->getMember();

?>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th colspan="2">发票信息</th>
            </tr>
            <tr>
                <td width="20%">抬头:</td>
                <td width="80%"><strong><?php echo $invoice->getTitle(); ?></strong></td>
            </tr>
            <tr>
                <td>金额:</td>
                <td><strong>&yen; <?php echo $invoice->getMoney(); ?></strong></td>
            </tr>
            <tr>
                <td>申请人:</td>
                <td><?php echo $member->getMemberName(); ?></td>
            </tr>
            <tr>
                <td>帐号:</td>
                <td><?php echo $member->getMemberEmail(); ?></td>
            </tr>
            <tr>
                <td>备注信息:</td>
                <td><?php echo nl2br($invoice->getNote()); ?></td>
            </tr>
            <tr>
                <td colspan="2">
                    <form method="post">
                        <div class="form-group">
                            <label for="status">更新状态</label>
                            <select name="status" id="status" class="form-control">
                                <option value="0" selected>选择更新状态</option>
                                <option value="<?php echo \WeChat\Entity\Invoice::STATUS_INVOICE_PRINT; ?>">已安排打印中</option>
                                <option value="<?php echo \WeChat\Entity\Invoice::STATUS_INVOICE_DELIVER; ?>">已安排邮递</option>
                                <option value="<?php echo \WeChat\Entity\Invoice::STATUS_INVOICE_REFUSED; ?>">驳回开票申请</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="note">增加备注</label>
                            <input type="text" name="note" class="form-control" id="note" placeholder="">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </form>
                </td>
            </tr>
        </table>
    </div>
</div>
